import React from 'react';
import { formatDateJPKanji, formatDateShort } from '@/lib/utils/format-date';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
  pdf,
} from '@react-pdf/renderer';
import { type BodyMapSelectionData } from './BodyMapSelector';
import { MEDICAL_DEPARTMENTS, BODY_PARTS } from '@/lib/body-map-config';

// 注册中文字体 - 简体中文 Noto Sans SC
Font.register({
  family: 'NotoSansSC',
  fonts: [
    {
      src: 'https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-sc@latest/chinese-simplified-400-normal.ttf',
      fontWeight: 400,
    },
    {
      src: 'https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-sc@latest/chinese-simplified-700-normal.ttf',
      fontWeight: 700,
    },
  ],
});

// 注册日文字体 - Noto Sans JP
Font.register({
  family: 'NotoSansJP',
  fonts: [
    {
      src: 'https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-jp@latest/japanese-400-normal.ttf',
      fontWeight: 400,
    },
    {
      src: 'https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-jp@latest/japanese-700-normal.ttf',
      fontWeight: 700,
    },
  ],
});

// 注册繁体中文字体 - Noto Sans TC
Font.register({
  family: 'NotoSansTC',
  fonts: [
    {
      src: 'https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-tc@latest/chinese-traditional-400-normal.ttf',
      fontWeight: 400,
    },
    {
      src: 'https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-tc@latest/chinese-traditional-700-normal.ttf',
      fontWeight: 700,
    },
  ],
});

// 完全禁用连字符 - 返回整个单词不分割，避免出现 "-" 符号
Font.registerHyphenationCallback((word: string) => {
  // 返回整个单词作为单一元素，禁止在任何位置断词
  return [word];
});

// 清理 Markdown 语法的工具函数
function cleanMarkdown(text: string): string {
  if (!text) return '';
  return text
    .replace(/\*\*/g, '')  // 移除 **
    .replace(/\*/g, '')    // 移除 *
    .replace(/##/g, '')    // 移除 ##
    .replace(/#/g, '')     // 移除 #
    .replace(/`/g, '')     // 移除 `
    .replace(/---/g, '')   // 移除 ---
    .replace(/\n\n+/g, '\n') // 多个换行变单个
    .trim();
}

// CJK 文本自动换行处理 - 在 CJK 字符之间插入零宽空格
function wrapChinese(text: string): string {
  if (!text) return '';
  let cleaned = cleanMarkdown(text);

  // 移除 AI 生成内容中可能存在的多余连字符
  cleaned = cleaned
    .replace(/\s*-\s*$/gm, '')     // 移除行末的连字符
    .replace(/^\s*-\s*/gm, '')     // 移除行首的连字符（除非是列表）
    .replace(/\s+-\s+/g, ' ')      // 移除独立的连字符
    .replace(/([^\s])-([^\s])/g, '$1$2')  // 移除单词中间不必要的连字符

  // CJK 字符范围（汉字 + 平假名 + 片假名）
  const isCJK = (char: string) => /[\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]/.test(char);
  // 不应该在其前面换行的字符（右括号、逗号、句号等，含日文标点）
  const noBreakBefore = (char: string) => /[，。！？；：、）】》'"」』\]\),.!?;:\u3002\uff0c\u3001\u3002]/.test(char);

  let result = '';
  for (let i = 0; i < cleaned.length; i++) {
    const char = cleaned[i];
    const nextChar = i < cleaned.length - 1 ? cleaned[i + 1] : '';

    result += char;

    // 在 CJK 字符后面插入零宽空格（允许换行点）
    // 但不在标点符号前换行
    if (isCJK(char) && nextChar && !noBreakBefore(nextChar)) {
      result += '\u200B';
    }
  }
  return result;
}

// PDF 多语言翻译
type PDFLanguage = 'ja' | 'zh-CN' | 'zh-TW' | 'en';

const pdfTranslations: Record<string, Record<PDFLanguage, string>> = {
  // Risk labels
  riskLow: {
    ja: '低リスク',
    'zh-CN': '低风险',
    'zh-TW': '低風險',
    en: 'Low Risk',
  },
  riskMedium: {
    ja: '中リスク',
    'zh-CN': '中风险',
    'zh-TW': '中風險',
    en: 'Medium Risk',
  },
  riskHigh: {
    ja: '高リスク',
    'zh-CN': '高风险',
    'zh-TW': '高風險',
    en: 'High Risk',
  },
  // Cover page
  coverTitle: {
    ja: 'AI 健康評価レポート',
    'zh-CN': 'AI 健康评估报告',
    'zh-TW': 'AI 健康評估報告',
    en: 'AI Health Assessment Report',
  },
  coverSubtitle: {
    ja: 'PERSONALIZED HEALTH ASSESSMENT REPORT',
    'zh-CN': 'PERSONALIZED HEALTH ASSESSMENT REPORT',
    'zh-TW': 'PERSONALIZED HEALTH ASSESSMENT REPORT',
    en: 'PERSONALIZED HEALTH ASSESSMENT REPORT',
  },
  reportId: {
    ja: 'レポート番号',
    'zh-CN': '报告编号',
    'zh-TW': '報告編號',
    en: 'Report ID',
  },
  assessmentDate: {
    ja: '評価日',
    'zh-CN': '评估日期',
    'zh-TW': '評估日期',
    en: 'Assessment Date',
  },
  partnerInstitution: {
    ja: '提携医療機関',
    'zh-CN': '合作医疗机构',
    'zh-TW': '合作醫療機構',
    en: 'Partner Institution',
  },
  partnerInstitutionName: {
    ja: '日本精密健診センター',
    'zh-CN': '日本精密健检中心',
    'zh-TW': '日本精密健檢中心',
    en: 'Japan Precision Health Check Center',
  },
  healthRiskAssessment: {
    ja: '健康リスク評価',
    'zh-CN': '健康风险评估',
    'zh-TW': '健康風險評估',
    en: 'Health Risk Assessment',
  },
  coverDisclaimer: {
    ja: '本レポートはAI分析システムにより生成されたものであり、健康参考情報としてのみ提供されます。医療診断の根拠とはなりません',
    'zh-CN': '本报告由 AI 智能分析系统生成，仅供健康参考，不构成医疗诊断依据',
    'zh-TW': '本報告由 AI 智慧分析系統生成，僅供健康參考，不構成醫療診斷依據',
    en: 'This report is generated by an AI analysis system for health reference only and does not constitute medical diagnosis',
  },
  // Section titles
  symptomAreas: {
    ja: '症状部位',
    'zh-CN': '症状部位',
    'zh-TW': '症狀部位',
    en: 'Symptom Areas',
  },
  specificSymptoms: {
    ja: '具体的な症状',
    'zh-CN': '具体症状',
    'zh-TW': '具體症狀',
    en: 'Specific Symptoms',
  },
  recommendedDepartments: {
    ja: '推奨受診科',
    'zh-CN': '推荐就诊科室',
    'zh-TW': '推薦就診科室',
    en: 'Recommended Departments',
  },
  suggestedExaminations: {
    ja: '推奨検査項目',
    'zh-CN': '建议检查项目',
    'zh-TW': '建議檢查項目',
    en: 'Suggested Examinations',
  },
  advancedTreatment: {
    ja: '日本先端治療の提案',
    'zh-CN': '日本先端治疗建议',
    'zh-TW': '日本先端治療建議',
    en: 'Japan Advanced Treatment Suggestions',
  },
  nextSteps: {
    ja: '次のステップ',
    'zh-CN': '下一步建议',
    'zh-TW': '下一步建議',
    en: 'Next Steps',
  },
  recommendedHospitals: {
    ja: '推奨医療機関',
    'zh-CN': '推荐医疗机构',
    'zh-TW': '推薦醫療機構',
    en: 'Recommended Hospitals',
  },
  suitableFor: {
    ja: '適応：',
    'zh-CN': '适合：',
    'zh-TW': '適合：',
    en: 'Suitable for: ',
  },
  importantDisclaimer: {
    ja: '重要事項',
    'zh-CN': '重要声明',
    'zh-TW': '重要聲明',
    en: 'Important Disclaimer',
  },
  defaultDisclaimer: {
    ja: '本レポートはAI分析技術に基づいて生成されており、健康リスクの参考情報を提供することを目的としています。専門的な医療診断に代わるものではありません。健康上の懸念がある場合は、必ず専門の医療従事者にご相談ください。',
    'zh-CN': '本报告基于 AI 分析技术生成，旨在提供健康风险参考，不能替代专业医疗诊断。如有任何健康疑虑，请务必咨询专业医疗人员。',
    'zh-TW': '本報告基於 AI 分析技術生成，旨在提供健康風險參考，不能替代專業醫療診斷。如有任何健康疑慮，請務必諮詢專業醫療人員。',
    en: 'This report is generated based on AI analysis technology and is intended to provide health risk reference only. It cannot replace professional medical diagnosis. If you have any health concerns, please consult a medical professional.',
  },
  bookHealthCheck: {
    ja: '日本精密健診を予約する',
    'zh-CN': '预约日本精密健检',
    'zh-TW': '預約日本精密健檢',
    en: 'Book Japan Health Check',
  },
  // Page numbers
  page2: {
    ja: '2 ページ',
    'zh-CN': '第 2 页',
    'zh-TW': '第 2 頁',
    en: 'Page 2',
  },
  page3: {
    ja: '3 ページ',
    'zh-CN': '第 3 页',
    'zh-TW': '第 3 頁',
    en: 'Page 3',
  },
  page4: {
    ja: '4 ページ',
    'zh-CN': '第 4 页',
    'zh-TW': '第 4 頁',
    en: 'Page 4',
  },
};

// 配色方案
const colors = {
  primary: '#0c1829',
  primaryLight: '#1a2f4a',
  gold: '#c9a961',
  goldLight: '#d4bc7e',
  textPrimary: '#1a1a1a',
  textSecondary: '#4a4a4a',
  textMuted: '#7a7a7a',
  textLight: '#ffffff',
  bgCream: '#faf8f5',
  bgWarm: '#f5f2ed',
  bgCard: '#ffffff',
  riskLow: '#2d5a4a',
  riskLowBg: '#e8f3ef',
  riskMedium: '#8b6914',
  riskMediumBg: '#fef7e6',
  riskHigh: '#8b2635',
  riskHighBg: '#fce8eb',
  divider: '#e5e0d8',
};

// 样式定义
const styles = StyleSheet.create({
  page: {
    fontFamily: 'NotoSansSC',
    fontSize: 10,
    backgroundColor: colors.bgCream,
    paddingLeft: 50,
    paddingRight: 55,
    paddingVertical: 45,
  },

  // 封面页
  coverPage: {
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  coverHeader: {
    backgroundColor: colors.primary,
    height: 260,
    paddingHorizontal: 40,
    paddingTop: 50,
  },
  coverBrand: {
    fontSize: 24,
    fontWeight: 700,
    color: colors.gold,
    letterSpacing: 3,
    marginBottom: 30,
  },
  coverTitle: {
    fontSize: 28,
    fontWeight: 700,
    color: colors.textLight,
    marginBottom: 8,
  },
  coverSubtitle: {
    fontSize: 11,
    color: colors.goldLight,
    letterSpacing: 1,
  },
  coverGoldBar: {
    height: 4,
    backgroundColor: colors.gold,
  },
  coverBody: {
    paddingHorizontal: 40,
    paddingTop: 40,
  },
  coverInfoBox: {
    backgroundColor: colors.bgCard,
    padding: 25,
    marginBottom: 30,
    borderLeftWidth: 3,
    borderLeftColor: colors.gold,
  },
  coverInfoRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  coverLabel: {
    width: 80,
    fontSize: 10,
    color: colors.textMuted,
  },
  coverValue: {
    flex: 1,
    fontSize: 11,
    fontWeight: 700,
    color: colors.textPrimary,
  },
  coverRiskBox: {
    alignItems: 'center',
    paddingVertical: 30,
  },
  coverRiskLabel: {
    fontSize: 10,
    color: colors.textMuted,
    marginBottom: 12,
    letterSpacing: 1,
  },
  riskBadge: {
    paddingHorizontal: 35,
    paddingVertical: 12,
  },
  riskBadgeLow: {
    backgroundColor: colors.riskLowBg,
    borderLeftWidth: 4,
    borderLeftColor: colors.riskLow,
  },
  riskBadgeMedium: {
    backgroundColor: colors.riskMediumBg,
    borderLeftWidth: 4,
    borderLeftColor: colors.riskMedium,
  },
  riskBadgeHigh: {
    backgroundColor: colors.riskHighBg,
    borderLeftWidth: 4,
    borderLeftColor: colors.riskHigh,
  },
  riskText: {
    fontSize: 16,
    fontWeight: 700,
    letterSpacing: 2,
  },
  riskTextLow: { color: colors.riskLow },
  riskTextMedium: { color: colors.riskMedium },
  riskTextHigh: { color: colors.riskHigh },
  coverFooter: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    paddingTop: 12,
  },
  coverFooterText: {
    fontSize: 8,
    color: colors.textMuted,
    textAlign: 'center',
  },

  // 页眉
  pageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 25,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  headerBrand: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.gold,
  },
  headerTitle: {
    fontSize: 10,
    color: colors.textMuted,
  },

  // 章节
  section: {
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionNum: {
    width: 22,
    height: 22,
    backgroundColor: colors.primary,
    color: colors.textLight,
    fontSize: 9,
    fontWeight: 700,
    textAlign: 'center',
    marginRight: 10,
    paddingTop: 5,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: colors.textPrimary,
  },
  sectionBar: {
    width: 35,
    height: 2,
    backgroundColor: colors.gold,
    marginTop: 6,
  },

  // 内容卡片
  card: {
    backgroundColor: colors.bgCard,
    padding: 14,
    paddingRight: 16,
    marginBottom: 12,
    borderLeftWidth: 3,
    borderLeftColor: colors.gold,
    width: '100%',
  },
  cardAlt: {
    backgroundColor: colors.bgWarm,
    padding: 14,
    paddingRight: 16,
    marginBottom: 12,
    width: '100%',
  },
  cardText: {
    fontSize: 8.5,
    color: colors.textSecondary,
    lineHeight: 1.7,
  },

  // 列表
  listItem: {
    flexDirection: 'row',
    marginBottom: 10,
    width: '100%',
  },
  listNum: {
    width: 18,
    height: 18,
    backgroundColor: colors.primaryLight,
    color: colors.textLight,
    fontSize: 8,
    fontWeight: 700,
    textAlign: 'center',
    marginRight: 8,
    paddingTop: 4,
    flexShrink: 0,
  },
  listDot: {
    width: 5,
    height: 5,
    backgroundColor: colors.gold,
    marginRight: 8,
    marginTop: 5,
    flexShrink: 0,
  },
  listText: {
    flex: 1,
    fontSize: 8.5,
    color: colors.textSecondary,
    lineHeight: 1.6,
    flexShrink: 1,
    flexWrap: 'wrap',
  },

  // 科室
  deptCard: {
    backgroundColor: colors.bgCard,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: colors.primaryLight,
  },
  deptName: {
    fontSize: 11,
    fontWeight: 700,
    color: colors.textPrimary,
    marginBottom: 4,
  },
  deptDesc: {
    fontSize: 9,
    color: colors.textMuted,
    marginBottom: 6,
  },
  deptTests: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  testTag: {
    fontSize: 8,
    color: colors.primaryLight,
    backgroundColor: '#e8eef5',
    paddingHorizontal: 6,
    paddingVertical: 3,
    marginRight: 4,
    marginBottom: 3,
  },

  // 医院
  hospitalCard: {
    backgroundColor: colors.bgCard,
    padding: 14,
    marginBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: colors.gold,
  },
  hospitalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  hospitalName: {
    fontSize: 11,
    fontWeight: 700,
    color: colors.textPrimary,
  },
  hospitalLoc: {
    fontSize: 9,
    fontWeight: 700,
    color: colors.gold,
  },
  hospitalTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  hospitalTag: {
    fontSize: 8,
    color: colors.textSecondary,
    backgroundColor: colors.bgWarm,
    paddingHorizontal: 6,
    paddingVertical: 3,
    marginRight: 4,
    marginBottom: 3,
  },
  hospitalFit: {
    fontSize: 9,
    color: colors.textMuted,
    marginTop: 6,
  },

  // 症状
  symptomBox: {
    backgroundColor: colors.bgCard,
    padding: 16,
  },
  symptomGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  symptomItem: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '50%',
    marginBottom: 6,
  },
  symptomDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
    backgroundColor: colors.riskMedium,
  },
  symptomText: {
    fontSize: 10,
    color: colors.textSecondary,
  },

  // 免责声明
  disclaimer: {
    backgroundColor: colors.bgWarm,
    padding: 16,
    marginTop: 15,
    borderTopWidth: 2,
    borderTopColor: colors.gold,
  },
  disclaimerTitle: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.textPrimary,
    marginBottom: 6,
  },
  disclaimerText: {
    fontSize: 8,
    color: colors.textMuted,
    lineHeight: 1.5,
  },

  // CTA
  cta: {
    backgroundColor: colors.primary,
    padding: 20,
    marginTop: 15,
    alignItems: 'center',
  },
  ctaTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: colors.gold,
    marginBottom: 6,
  },
  ctaText: {
    fontSize: 9,
    color: colors.textLight,
    textAlign: 'center',
  },

  // 页脚
  footer: {
    position: 'absolute',
    bottom: 25,
    left: 50,
    right: 55,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  footerText: {
    fontSize: 8,
    color: colors.textMuted,
  },
  footerBrand: {
    fontSize: 8,
    fontWeight: 700,
    color: colors.gold,
  },
});

interface HealthReportPDFProps {
  reportData: {
    language?: PDFLanguage;
    id: string;
    createdAt: string;
    userEmail: string;
    bodyMapData?: BodyMapSelectionData;
    analysisResult: {
      riskLevel: 'low' | 'medium' | 'high';
      riskSummary: string;
      recommendedDepartments?: string[];
      recommendedTests: string[];
      treatmentSuggestions: string[];
      recommendedHospitals: {
        name: string;
        location: string;
        features: string[];
        suitableFor: string;
      }[];
      nextSteps: string[];
      disclaimer: string;
    };
  };
}

// 根据语言选择字体
function getFontFamily(lang: PDFLanguage): string {
  switch (lang) {
    case 'ja': return 'NotoSansJP';
    case 'zh-TW': return 'NotoSansTC';
    default: return 'NotoSansSC';
  }
}

const HealthReportDocument: React.FC<HealthReportPDFProps> = ({ reportData }) => {
  const { analysisResult: rawResult, bodyMapData, createdAt, id, language } = reportData;
  const lang: PDFLanguage = language || 'zh-CN';
  const fontFamily = getFontFamily(lang);
  const pt = (key: string) => pdfTranslations[key]?.[lang] ?? pdfTranslations[key]?.['zh-CN'] ?? key;

  // AI 输出的数组字段可能为 undefined/null，统一做 fallback 防止 .map() 崩溃
  const analysisResult = {
    ...rawResult,
    riskLevel: rawResult.riskLevel || 'medium',
    riskSummary: rawResult.riskSummary || '',
    recommendedDepartments: rawResult.recommendedDepartments || [],
    recommendedTests: rawResult.recommendedTests || [],
    treatmentSuggestions: rawResult.treatmentSuggestions || [],
    recommendedHospitals: (rawResult.recommendedHospitals || []).map(h => ({
      ...h,
      features: h.features || [],
    })),
    nextSteps: rawResult.nextSteps || [],
    disclaimer: rawResult.disclaimer || '',
  };

  const riskConfig = {
    low: { badge: styles.riskBadgeLow, text: styles.riskTextLow, label: pt('riskLow') },
    medium: { badge: styles.riskBadgeMedium, text: styles.riskTextMedium, label: pt('riskMedium') },
    high: { badge: styles.riskBadgeHigh, text: styles.riskTextHigh, label: pt('riskHigh') },
  };


  const getBodyPartNames = () => {
    if (!bodyMapData?.selectedBodyParts) return [];
    return bodyMapData.selectedBodyParts
      .map((partId) => BODY_PARTS.find((p) => p.id === partId)?.name)
      .filter(Boolean) as string[];
  };

  const getDepartments = () => {
    // 优先使用问卷 bodyMapData 的科室推荐
    if (bodyMapData?.recommendedDepartments && bodyMapData.recommendedDepartments.length > 0) {
      const mapped = bodyMapData.recommendedDepartments
        .map((deptId) => MEDICAL_DEPARTMENTS.find((d) => d.id === deptId))
        .filter(Boolean);
      if (mapped.length > 0) return mapped;
    }
    // 回退：使用 AEMC pipeline 输出的科室名
    if (analysisResult.recommendedDepartments && analysisResult.recommendedDepartments.length > 0) {
      return analysisResult.recommendedDepartments.map((deptName) => ({
        name: deptName,
        description: '',
        recommendedTests: [] as string[],
      }));
    }
    return [];
  };

  // 动态编号：Section 02 (症状区域) 可能隐藏，后续编号自动调整
  const hasSymptomSection = !!(bodyMapData && bodyMapData.selectedBodyParts.length > 0);
  const secNum = (n: number) => {
    if (n <= 2) return String(n).padStart(2, '0');
    const adjusted = hasSymptomSection ? n : n - 1;
    return String(adjusted).padStart(2, '0');
  };

  return (
    <Document>
      {/* 封面 */}
      <Page size="A4" style={[styles.page, styles.coverPage, { fontFamily }]}>
        <View style={styles.coverHeader}>
          <Text style={styles.coverBrand}>新島交通株式会社</Text>
          <Text style={styles.coverTitle}>{pt('coverTitle')}</Text>
          <Text style={styles.coverSubtitle}>{pt('coverSubtitle')}</Text>
        </View>
        <View style={styles.coverGoldBar} />

        <View style={styles.coverBody}>
          <View style={styles.coverInfoBox}>
            <View style={styles.coverInfoRow}>
              <Text style={styles.coverLabel}>{pt('reportId')}</Text>
              <Text style={styles.coverValue}>{id.substring(0, 8).toUpperCase()}</Text>
            </View>
            <View style={styles.coverInfoRow}>
              <Text style={styles.coverLabel}>{pt('assessmentDate')}</Text>
              <Text style={styles.coverValue}>{formatDateJPKanji(createdAt)}</Text>
            </View>
            <View style={[styles.coverInfoRow, { marginBottom: 0 }]}>
              <Text style={styles.coverLabel}>{pt('partnerInstitution')}</Text>
              <Text style={styles.coverValue}>{pt('partnerInstitutionName')}</Text>
            </View>
          </View>

          <View style={styles.coverRiskBox}>
            <Text style={styles.coverRiskLabel}>{pt('healthRiskAssessment')}</Text>
            <View style={[styles.riskBadge, riskConfig[analysisResult.riskLevel].badge]}>
              <Text style={[styles.riskText, riskConfig[analysisResult.riskLevel].text]}>
                {riskConfig[analysisResult.riskLevel].label}
              </Text>
            </View>
          </View>
        </View>

        <View style={styles.coverFooter}>
          <Text style={styles.coverFooterText}>
            {pt('coverDisclaimer')}
          </Text>
        </View>
      </Page>

      {/* 第2页：风险分析 */}
      <Page size="A4" style={[styles.page, { fontFamily }]}>
        <View style={styles.pageHeader}>
          <Text style={styles.headerBrand}>新島交通</Text>
          <Text style={styles.headerTitle}>AI Health Assessment</Text>
        </View>

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionNum}>01</Text>
            <Text style={styles.sectionTitle}>{pt('healthRiskAssessment')}</Text>
          </View>
          <View style={styles.sectionBar} />
          <View style={[styles.card, { marginTop: 12 }]}>
            <Text style={styles.cardText}>{wrapChinese(analysisResult.riskSummary)}</Text>
          </View>
        </View>

        {bodyMapData && bodyMapData.selectedBodyParts.length > 0 && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Text style={styles.sectionNum}>02</Text>
              <Text style={styles.sectionTitle}>{pt('symptomAreas')}</Text>
            </View>
            <View style={styles.sectionBar} />
            <View style={[styles.symptomBox, { marginTop: 12 }]}>
              <View style={styles.symptomGrid}>
                {getBodyPartNames().map((name, idx) => (
                  <View key={idx} style={styles.symptomItem}>
                    <View style={styles.symptomDot} />
                    <Text style={styles.symptomText}>{name}</Text>
                  </View>
                ))}
              </View>
              {bodyMapData.selectedSymptoms.length > 0 && (
                <View style={{ marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.divider }}>
                  <Text style={{ fontSize: 10, fontWeight: 700, marginBottom: 8 }}>{pt('specificSymptoms')}</Text>
                  <View style={styles.symptomGrid}>
                    {bodyMapData.selectedSymptoms.map((symptom, idx) => (
                      <View key={idx} style={styles.symptomItem}>
                        <View style={styles.symptomDot} />
                        <Text style={styles.symptomText}>{symptom.name}</Text>
                      </View>
                    ))}
                  </View>
                </View>
              )}
            </View>
          </View>
        )}

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionNum}>{secNum(3)}</Text>
            <Text style={styles.sectionTitle}>{pt('recommendedDepartments')}</Text>
          </View>
          <View style={styles.sectionBar} />
          <View style={{ marginTop: 12 }}>
            {getDepartments().slice(0, 3).map((dept: any, idx) => (
              <View key={idx} style={styles.deptCard}>
                <Text style={styles.deptName}>{dept.name}</Text>
                <Text style={styles.deptDesc}>{dept.description}</Text>
                <View style={styles.deptTests}>
                  {dept.recommendedTests.slice(0, 4).map((test: string, i: number) => (
                    <Text key={i} style={styles.testTag}>{test}</Text>
                  ))}
                </View>
              </View>
            ))}
          </View>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>{formatDateShort(createdAt)}</Text>
          <Text style={styles.footerBrand}>新島交通株式会社</Text>
          <Text style={styles.footerText}>{pt('page2')}</Text>
        </View>
      </Page>

      {/* 第3页：检查建议 */}
      <Page size="A4" style={[styles.page, { fontFamily }]}>
        <View style={styles.pageHeader}>
          <Text style={styles.headerBrand}>新島交通</Text>
          <Text style={styles.headerTitle}>AI Health Assessment</Text>
        </View>

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionNum}>{secNum(4)}</Text>
            <Text style={styles.sectionTitle}>{pt('suggestedExaminations')}</Text>
          </View>
          <View style={styles.sectionBar} />
          <View style={[styles.card, { marginTop: 12 }]}>
            {analysisResult.recommendedTests.map((test, idx) => (
              <View key={idx} style={styles.listItem}>
                <Text style={styles.listNum}>{idx + 1}</Text>
                <Text style={styles.listText}>{wrapChinese(test)}</Text>
              </View>
            ))}
          </View>
        </View>

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionNum}>{secNum(5)}</Text>
            <Text style={styles.sectionTitle}>{pt('advancedTreatment')}</Text>
          </View>
          <View style={styles.sectionBar} />
          <View style={[styles.cardAlt, { marginTop: 12 }]}>
            {analysisResult.treatmentSuggestions.map((item, idx) => (
              <View key={idx} style={styles.listItem}>
                <View style={styles.listDot} />
                <Text style={styles.listText}>{wrapChinese(item)}</Text>
              </View>
            ))}
          </View>
        </View>

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionNum}>{secNum(6)}</Text>
            <Text style={styles.sectionTitle}>{pt('nextSteps')}</Text>
          </View>
          <View style={styles.sectionBar} />
          <View style={[styles.card, { marginTop: 12 }]}>
            {analysisResult.nextSteps.map((step, idx) => (
              <View key={idx} style={styles.listItem}>
                <Text style={styles.listNum}>{idx + 1}</Text>
                <Text style={styles.listText}>{wrapChinese(step)}</Text>
              </View>
            ))}
          </View>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>{formatDateShort(createdAt)}</Text>
          <Text style={styles.footerBrand}>新島交通株式会社</Text>
          <Text style={styles.footerText}>{pt('page3')}</Text>
        </View>
      </Page>

      {/* 第4页：推荐医院 */}
      <Page size="A4" style={[styles.page, { fontFamily }]}>
        <View style={styles.pageHeader}>
          <Text style={styles.headerBrand}>新島交通</Text>
          <Text style={styles.headerTitle}>AI Health Assessment</Text>
        </View>

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionNum}>{secNum(7)}</Text>
            <Text style={styles.sectionTitle}>{pt('recommendedHospitals')}</Text>
          </View>
          <View style={styles.sectionBar} />
          <View style={{ marginTop: 12 }}>
            {analysisResult.recommendedHospitals.map((hospital, idx) => (
              <View key={idx} style={styles.hospitalCard}>
                <View style={styles.hospitalRow}>
                  <Text style={styles.hospitalName}>{hospital.name}</Text>
                  <Text style={styles.hospitalLoc}>{hospital.location}</Text>
                </View>
                <View style={styles.hospitalTags}>
                  {hospital.features.map((f, i) => (
                    <Text key={i} style={styles.hospitalTag}>{f}</Text>
                  ))}
                </View>
                {hospital.suitableFor && (
                  <Text style={styles.hospitalFit}>{pt('suitableFor')}{hospital.suitableFor}</Text>
                )}
              </View>
            ))}
          </View>
        </View>

        <View style={styles.disclaimer}>
          <Text style={styles.disclaimerTitle}>{pt('importantDisclaimer')}</Text>
          <Text style={styles.disclaimerText}>
            {wrapChinese(analysisResult.disclaimer) ||
              wrapChinese(pt('defaultDisclaimer'))}
          </Text>
        </View>

        <View style={styles.cta}>
          <Text style={styles.ctaTitle}>{pt('bookHealthCheck')}</Text>
          <Text style={styles.ctaText}>www.niijima-koutsu.jp/medical</Text>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>© 2025 新島交通株式会社</Text>
          <Text style={styles.footerBrand}>新島交通株式会社</Text>
          <Text style={styles.footerText}>{pt('page4')}</Text>
        </View>
      </Page>
    </Document>
  );
};

export async function generateHealthReportPDF(
  reportData: HealthReportPDFProps['reportData']
): Promise<Blob> {
  const blob = await pdf(<HealthReportDocument reportData={reportData} />).toBlob();
  return blob;
}

export async function downloadHealthReportPDF(
  reportData: HealthReportPDFProps['reportData'],
  filename?: string
): Promise<void> {
  const blob = await generateHealthReportPDF(reportData);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `Niijima-Health-Report-${reportData.id.substring(0, 8).toUpperCase()}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export type { PDFLanguage };
export default HealthReportDocument;
