/**
 * 医疗套餐配置中心
 *
 * 重要：此文件仅用于前端展示和开发参考
 * 生产环境的价格和配置以数据库 medical_packages 表为准
 */

export interface MedicalPackageConfig {
  slug: string;
  nameZhTw: string;
  nameJa: string;
  nameEn: string;
  descriptionZhTw: string;
  /** 参考价格（日元），实际价格以数据库为准 */
  priceJpy: number;
  category: 'cancer_treatment' | 'health_checkup' | 'cosmetic_surgery' | 'other';
  sortOrder: number;
}

/**
 * 医疗套餐配置
 *
 * ⚠️ 警告：这些价格仅供前端展示使用
 * API 和支付流程必须从数据库读取实际价格
 */
export const MEDICAL_PACKAGES: Record<string, MedicalPackageConfig> = {
  'cancer-initial-consultation': {
    slug: 'cancer-initial-consultation',
    nameZhTw: '癌症治療 - 前期諮詢服務',
    nameJa: 'がん治療 - 初期相談サービス',
    nameEn: 'Cancer Treatment - Initial Consultation',
    descriptionZhTw: '資料翻譯、醫院諮詢、治療方案初步評估',
    priceJpy: 221000,
    category: 'cancer_treatment',
    sortOrder: 100,
  },
  'cancer-remote-consultation': {
    slug: 'cancer-remote-consultation',
    nameZhTw: '癌症治療 - 遠程會診服務',
    nameJa: 'がん治療 - 遠隔診療サービス',
    nameEn: 'Cancer Treatment - Remote Consultation',
    descriptionZhTw: '與日本醫生遠程視頻會診、討論治療方案、費用概算',
    priceJpy: 243000,
    category: 'cancer_treatment',
    sortOrder: 101,
  },

  // ─── 兵庫医大 咨询服务 ───
  'hyogo-initial-consultation': {
    slug: 'hyogo-initial-consultation',
    nameZhTw: '兵庫醫大 - 前期諮詢服務',
    nameJa: '兵庫医大 - 初期相談サービス',
    nameEn: 'Hyogo Medical - Initial Consultation',
    descriptionZhTw: '資料翻譯、兵庫醫大諮詢、治療方案初步評估',
    priceJpy: 221000,
    category: 'cancer_treatment',
    sortOrder: 110,
  },
  'hyogo-remote-consultation': {
    slug: 'hyogo-remote-consultation',
    nameZhTw: '兵庫醫大 - 遠程會診服務',
    nameJa: '兵庫医大 - 遠隔診療サービス',
    nameEn: 'Hyogo Medical - Remote Consultation',
    descriptionZhTw: '與兵庫醫大專科醫生遠程視頻會診、討論治療方案、費用概算',
    priceJpy: 243000,
    category: 'cancer_treatment',
    sortOrder: 111,
  },

  // ─── HELENE 干细胞诊所 咨询服务 ───
  'helene-initial-consultation': {
    slug: 'helene-initial-consultation',
    nameZhTw: 'HELENE診所 - 前期諮詢服務',
    nameJa: 'ヘレネクリニック - 初期相談サービス',
    nameEn: 'HELENE Clinic - Initial Consultation',
    descriptionZhTw: '病歷翻譯、診所諮詢、幹細胞治療方案評估、費用概算',
    priceJpy: 221000,
    category: 'other',
    sortOrder: 120,
  },
  'helene-remote-consultation': {
    slug: 'helene-remote-consultation',
    nameZhTw: 'HELENE診所 - 遠程診斷服務',
    nameJa: 'ヘレネクリニック - 遠隔診療サービス',
    nameEn: 'HELENE Clinic - Remote Consultation',
    descriptionZhTw: '與HELENE診所專科醫生遠程視頻會診、幹細胞治療方案評估、費用概算',
    priceJpy: 243000,
    category: 'other',
    sortOrder: 121,
  },

  // ─── 銀座鳳凰クリニック 咨询服务 ───
  'ginza-phoenix-initial-consultation': {
    slug: 'ginza-phoenix-initial-consultation',
    nameZhTw: '銀座鳳凰診所 - 前期諮詢服務',
    nameJa: '銀座鳳凰クリニック - 初期相談サービス',
    nameEn: 'Ginza Phoenix Clinic - Initial Consultation',
    descriptionZhTw: '病歷翻譯、診所諮詢、免疫細胞療法方案評估、費用概算',
    priceJpy: 221000,
    category: 'other',
    sortOrder: 130,
  },
  'ginza-phoenix-remote-consultation': {
    slug: 'ginza-phoenix-remote-consultation',
    nameZhTw: '銀座鳳凰診所 - 遠程診斷服務',
    nameJa: '銀座鳳凰クリニック - 遠隔診療サービス',
    nameEn: 'Ginza Phoenix Clinic - Remote Consultation',
    descriptionZhTw: '與銀座鳳凰クリニック專科醫生遠程視頻會診、免疫細胞療法方案評估、費用概算',
    priceJpy: 243000,
    category: 'other',
    sortOrder: 131,
  },

  // ─── W CLINIC men's 男性专科 咨询服务 ───
  'wclinic-mens-initial-consultation': {
    slug: 'wclinic-mens-initial-consultation',
    nameZhTw: 'W CLINIC men\'s - 前期諮詢服務',
    nameJa: 'Wクリニック メンズ - 初期相談サービス',
    nameEn: 'W CLINIC men\'s - Initial Consultation',
    descriptionZhTw: '病歷翻譯、植村教授初診評估、ED/LOH/AGA治療方案制定、費用概算',
    priceJpy: 221000,
    category: 'other',
    sortOrder: 140,
  },
  'wclinic-mens-remote-consultation': {
    slug: 'wclinic-mens-remote-consultation',
    nameZhTw: 'W CLINIC men\'s - 遠程診斷服務',
    nameJa: 'Wクリニック メンズ - 遠隔診療サービス',
    nameEn: 'W CLINIC men\'s - Remote Consultation',
    descriptionZhTw: '與植村天受教授遠程視頻會診、男性健康治療方案評估、個性化診療計劃',
    priceJpy: 243000,
    category: 'other',
    sortOrder: 141,
  },

  // ─── W CLINIC men's AGA·育毛治療 ───
  'wclinic-aga-original-set': {
    slug: 'wclinic-aga-original-set',
    nameZhTw: 'W Original AGA口服套裝',
    nameJa: 'Wオリジナル AGA内服セット',
    nameEn: 'W Original AGA Oral Set',
    descriptionZhTw: 'W CLINIC原創AGA口服藥物套裝·30日份',
    priceJpy: 14500,
    category: 'other',
    sortOrder: 142,
  },
  'wclinic-propecia': {
    slug: 'wclinic-propecia',
    nameZhTw: 'Propecia',
    nameJa: 'プロペシア',
    nameEn: 'Propecia',
    descriptionZhTw: 'AGA治療·Propecia口服藥·30日份',
    priceJpy: 9350,
    category: 'other',
    sortOrder: 143,
  },
  'wclinic-finasteride': {
    slug: 'wclinic-finasteride',
    nameZhTw: 'Finasteride (1.3mg)',
    nameJa: 'フィナステリド (1.3mg)',
    nameEn: 'Finasteride (1.3mg)',
    descriptionZhTw: 'AGA治療·非那雄胺1.3mg·30日份',
    priceJpy: 3500,
    category: 'other',
    sortOrder: 144,
  },
  'wclinic-dutasteride': {
    slug: 'wclinic-dutasteride',
    nameZhTw: 'Dutasteride (0.5mg)',
    nameJa: 'デュタステリド (0.5mg)',
    nameEn: 'Dutasteride (0.5mg)',
    descriptionZhTw: 'AGA治療·度他雄胺0.5mg·30日份',
    priceJpy: 6800,
    category: 'other',
    sortOrder: 145,
  },
  'wclinic-minoxidil': {
    slug: 'wclinic-minoxidil',
    nameZhTw: 'Minoxidil (5mg)',
    nameJa: 'ミノキシジル (5mg)',
    nameEn: 'Minoxidil (5mg)',
    descriptionZhTw: 'AGA治療·米諾地爾5mg口服·30日份',
    priceJpy: 7700,
    category: 'other',
    sortOrder: 146,
  },
  'wclinic-hydra-gentle-scalp': {
    slug: 'wclinic-hydra-gentle-scalp',
    nameZhTw: 'Hydra Gentle 頭皮',
    nameJa: 'ハイドラジェントル 頭皮',
    nameEn: 'Hydra Gentle Scalp',
    descriptionZhTw: '頭皮深層清潔·Hydra Gentle·初回體驗價',
    priceJpy: 11000,
    category: 'other',
    sortOrder: 147,
  },
  'wclinic-meso-gun-stem-cell': {
    slug: 'wclinic-meso-gun-stem-cell',
    nameZhTw: 'U-225 Meso Gun 幹細胞',
    nameJa: 'U-225メソガン 幹細胞上清液',
    nameEn: 'U-225 Meso Gun (Stem Cell)',
    descriptionZhTw: '幹細胞上清液注入·U-225 Meso Gun·每次',
    priceJpy: 33000,
    category: 'other',
    sortOrder: 148,
  },
  'wclinic-hair-tattoo-trial': {
    slug: 'wclinic-hair-tattoo-trial',
    nameZhTw: '頭皮微色素 體驗',
    nameJa: 'ヘアタトゥー トライアル',
    nameEn: 'Scalp Micropigmentation Trial',
    descriptionZhTw: '頭皮微色素紋繡·體驗價',
    priceJpy: 9900,
    category: 'other',
    sortOrder: 149,
  },

  // ─── W CLINIC men's アンチエイジング・美容 ───
  'wclinic-hifu-light': {
    slug: 'wclinic-hifu-light',
    nameZhTw: 'HIFU Light (200shot)',
    nameJa: 'HIFU ライト (200shot)',
    nameEn: 'HIFU Light (200 shots)',
    descriptionZhTw: 'HIFU超聲波提拉·200發·輕量版',
    priceJpy: 27500,
    category: 'other',
    sortOrder: 150,
  },
  'wclinic-hifu-standard': {
    slug: 'wclinic-hifu-standard',
    nameZhTw: 'HIFU Standard (600shot)',
    nameJa: 'HIFU スタンダード (600shot)',
    nameEn: 'HIFU Standard (600 shots)',
    descriptionZhTw: 'HIFU超聲波提拉·600發·標準版',
    priceJpy: 88000,
    category: 'other',
    sortOrder: 151,
  },
  'wclinic-hifu-custom': {
    slug: 'wclinic-hifu-custom',
    nameZhTw: 'HIFU 訂製 (無限shot)',
    nameJa: 'HIFU オーダーメイド (無制限)',
    nameEn: 'HIFU Custom (Unlimited)',
    descriptionZhTw: 'HIFU超聲波提拉·無限發數·全面訂製',
    priceJpy: 165000,
    category: 'other',
    sortOrder: 152,
  },
  'wclinic-botox-vista': {
    slug: 'wclinic-botox-vista',
    nameZhTw: 'Botox Vista (Allergan)',
    nameJa: 'ボトックスビスタ (Allergan)',
    nameEn: 'Botox Vista (Allergan)',
    descriptionZhTw: 'Allergan正品肉毒桿菌·最低價起',
    priceJpy: 22000,
    category: 'other',
    sortOrder: 153,
  },
  'wclinic-hyaluronic-acid': {
    slug: 'wclinic-hyaluronic-acid',
    nameZhTw: '玻尿酸注射',
    nameJa: 'ヒアルロン酸注射',
    nameEn: 'Hyaluronic Acid Injection',
    descriptionZhTw: '玻尿酸注射填充·每支',
    priceJpy: 88000,
    category: 'other',
    sortOrder: 154,
  },
  'wclinic-profhilo': {
    slug: 'wclinic-profhilo',
    nameZhTw: 'Profhilo',
    nameJa: 'プロファイロ PROFHILO',
    nameEn: 'Profhilo',
    descriptionZhTw: 'Profhilo玻尿酸肌底注射·每次',
    priceJpy: 132000,
    category: 'other',
    sortOrder: 155,
  },
  'wclinic-tesslift': {
    slug: 'wclinic-tesslift',
    nameZhTw: 'Tesslift (線雕)',
    nameJa: 'テスリフト (糸リフト)',
    nameEn: 'Tesslift (Thread Lift)',
    descriptionZhTw: 'Tesslift線雕提升·每根',
    priceJpy: 66000,
    category: 'other',
    sortOrder: 156,
  },
  'wclinic-collagen-lift': {
    slug: 'wclinic-collagen-lift',
    nameZhTw: '膠原蛋白提升',
    nameJa: 'コラーゲンリフト',
    nameEn: 'Collagen Lift',
    descriptionZhTw: '膠原蛋白線雕提升·每根',
    priceJpy: 19800,
    category: 'other',
    sortOrder: 157,
  },
  'wclinic-sunekos': {
    slug: 'wclinic-sunekos',
    nameZhTw: 'Sunekos注射',
    nameJa: 'スネコス注射',
    nameEn: 'Sunekos Injection',
    descriptionZhTw: 'Sunekos再生注射·每次',
    priceJpy: 55000,
    category: 'other',
    sortOrder: 158,
  },
  'wclinic-rejuran': {
    slug: 'wclinic-rejuran',
    nameZhTw: 'Rejuran (高濃度鮭魚DNA)',
    nameJa: 'リジュラン (高濃度サーモンDNA)',
    nameEn: 'Rejuran (Salmon DNA)',
    descriptionZhTw: 'Rejuran鮭魚DNA肌膚再生·2cc',
    priceJpy: 88000,
    category: 'other',
    sortOrder: 159,
  },

  // ─── W CLINIC men's 点滴・注射 ───
  'wclinic-exosome-100b': {
    slug: 'wclinic-exosome-100b',
    nameZhTw: '外泌體 1,000億',
    nameJa: 'エクソソーム 1,000億個',
    nameEn: 'Exosome 100B',
    descriptionZhTw: '外泌體點滴·1,000億個·抗衰再生',
    priceJpy: 123200,
    category: 'other',
    sortOrder: 160,
  },
  'wclinic-exosome-200b': {
    slug: 'wclinic-exosome-200b',
    nameZhTw: '外泌體 2,000億',
    nameJa: 'エクソソーム 2,000億個',
    nameEn: 'Exosome 200B',
    descriptionZhTw: '外泌體點滴·2,000億個·高劑量抗衰',
    priceJpy: 220000,
    category: 'other',
    sortOrder: 161,
  },
  'wclinic-nmn-100mg': {
    slug: 'wclinic-nmn-100mg',
    nameZhTw: 'NMN點滴 100mg',
    nameJa: 'NMN点滴 100mg',
    nameEn: 'NMN IV 100mg',
    descriptionZhTw: 'NMN抗衰點滴·100mg·初回體驗價',
    priceJpy: 32780,
    category: 'other',
    sortOrder: 162,
  },
  'wclinic-nmn-300mg': {
    slug: 'wclinic-nmn-300mg',
    nameZhTw: 'NMN點滴 300mg',
    nameJa: 'NMN点滴 300mg',
    nameEn: 'NMN IV 300mg',
    descriptionZhTw: 'NMN抗衰點滴·300mg·每次',
    priceJpy: 66000,
    category: 'other',
    sortOrder: 163,
  },
  'wclinic-stem-cell-supernatant': {
    slug: 'wclinic-stem-cell-supernatant',
    nameZhTw: '幹細胞培養上清液',
    nameJa: '幹細胞培養上清液',
    nameEn: 'Stem Cell Supernatant',
    descriptionZhTw: '幹細胞培養上清液點滴·初回體驗價',
    priceJpy: 33000,
    category: 'other',
    sortOrder: 164,
  },
  'wclinic-vitamin-c-iv': {
    slug: 'wclinic-vitamin-c-iv',
    nameZhTw: '高濃度維生素C (12.5g)',
    nameJa: '高濃度ビタミンC (12.5g)',
    nameEn: 'High-Dose Vitamin C (12.5g)',
    descriptionZhTw: '高濃度維生素C靜脈點滴·12.5g·初回體驗價',
    priceJpy: 8800,
    category: 'other',
    sortOrder: 165,
  },
  'wclinic-ozone-cleansing': {
    slug: 'wclinic-ozone-cleansing',
    nameZhTw: '血液臭氧淨化',
    nameJa: '血液オゾンクレンジング',
    nameEn: 'Blood Ozone Cleansing',
    descriptionZhTw: '血液臭氧淨化療法·初回體驗價',
    priceJpy: 16500,
    category: 'other',
    sortOrder: 166,
  },
  'wclinic-placenta-injection': {
    slug: 'wclinic-placenta-injection',
    nameZhTw: '胎盤素注射',
    nameJa: 'プラセンタ注射',
    nameEn: 'Placenta Injection',
    descriptionZhTw: '胎盤素注射·每安瓶',
    priceJpy: 1320,
    category: 'other',
    sortOrder: 167,
  },

  // ─── W CLINIC men's レーザー・美肌 ───
  'wclinic-laser-full-body': {
    slug: 'wclinic-laser-full-body',
    nameZhTw: '雷射脫毛 全身',
    nameJa: 'レーザー脱毛 全身 (顔VIO除)',
    nameEn: 'Laser Hair Removal (Full Body)',
    descriptionZhTw: '全身雷射脫毛（臉部VIO除外）',
    priceJpy: 55000,
    category: 'other',
    sortOrder: 168,
  },
  'wclinic-laser-beard': {
    slug: 'wclinic-laser-beard',
    nameZhTw: '雷射脫毛 鬍鬚',
    nameJa: 'レーザー脱毛 ひげセット',
    nameEn: 'Laser Beard Set',
    descriptionZhTw: '鬍鬚雷射脫毛套裝',
    priceJpy: 9900,
    category: 'other',
    sortOrder: 169,
  },
  'wclinic-pico-spot': {
    slug: 'wclinic-pico-spot',
    nameZhTw: 'Pico Spot 除斑 (1cm²)',
    nameJa: 'ピコスポット シミ取り (1cm²)',
    nameEn: 'Pico Spot (1cm²)',
    descriptionZhTw: 'Pico雷射除斑·每1cm²起',
    priceJpy: 5500,
    category: 'other',
    sortOrder: 170,
  },
  'wclinic-dermapen4': {
    slug: 'wclinic-dermapen4',
    nameZhTw: 'Dermapen 4 (毛孔·痘疤)',
    nameJa: 'ダーマペン4 (毛穴・ニキビ跡)',
    nameEn: 'Dermapen 4 (Pores/Acne Scars)',
    descriptionZhTw: 'Dermapen 4微針治療·毛孔/痘疤改善·初回體驗價',
    priceJpy: 17600,
    category: 'other',
    sortOrder: 171,
  },
  'wclinic-intragen-rf': {
    slug: 'wclinic-intragen-rf',
    nameZhTw: 'Intragen RF',
    nameJa: 'イントラジェン RF',
    nameEn: 'Intragen RF',
    descriptionZhTw: 'Intragen RF射頻緊膚·初回體驗價',
    priceJpy: 33000,
    category: 'other',
    sortOrder: 172,
  },
  'wclinic-co2-laser': {
    slug: 'wclinic-co2-laser',
    nameZhTw: 'CO2雷射 (痣)',
    nameJa: 'CO2レーザー (ほくろ)',
    nameEn: 'CO2 Laser (Moles)',
    descriptionZhTw: 'CO2雷射去痣·價格依大小',
    priceJpy: 3300,
    category: 'other',
    sortOrder: 173,
  },
  'wclinic-ptp-toning': {
    slug: 'wclinic-ptp-toning',
    nameZhTw: 'PTP Toning 全臉',
    nameJa: 'PTPトーニング 全顔',
    nameEn: 'PTP Toning (Full Face)',
    descriptionZhTw: 'PTP Toning全臉嫩膚·初回體驗價',
    priceJpy: 13200,
    category: 'other',
    sortOrder: 174,
  },

  // ─── W CLINIC men's その他の診療 ───
  'wclinic-night-laser': {
    slug: 'wclinic-night-laser',
    nameZhTw: 'W Night Laser (鼾症)',
    nameJa: 'Wナイトレーザー (いびき治療)',
    nameEn: 'W Night Laser (Snoring)',
    descriptionZhTw: 'W Night Laser打鼾治療·初回體驗價',
    priceJpy: 33000,
    category: 'other',
    sortOrder: 175,
  },
  'wclinic-rybelsus-3mg': {
    slug: 'wclinic-rybelsus-3mg',
    nameZhTw: 'Rybelsus GLP-1 減重 (3mg)',
    nameJa: 'リベルサス GLP-1 ダイエット (3mg)',
    nameEn: 'Rybelsus GLP-1 Diet (3mg)',
    descriptionZhTw: 'GLP-1減重藥物Rybelsus 3mg·30錠',
    priceJpy: 11880,
    category: 'other',
    sortOrder: 176,
  },
  'wclinic-hyperhidrosis-botox': {
    slug: 'wclinic-hyperhidrosis-botox',
    nameZhTw: '多汗症肉毒 雙腋 (保險)',
    nameJa: '多汗症ボトックス 両ワキ (保険適用)',
    nameEn: 'Hyperhidrosis Botox (Insurance)',
    descriptionZhTw: '多汗症肉毒桿菌治療·雙腋·保險適用',
    priceJpy: 23000,
    category: 'other',
    sortOrder: 177,
  },
  'wclinic-testosterone-test': {
    slug: 'wclinic-testosterone-test',
    nameZhTw: '男性荷爾蒙檢測 (睾酮)',
    nameJa: '男性ホルモン検査 (テストステロン)',
    nameEn: 'Testosterone Test',
    descriptionZhTw: '男性荷爾蒙（睾酮水平）血液檢測',
    priceJpy: 11000,
    category: 'other',
    sortOrder: 178,
  },
  'wclinic-food-allergy-test': {
    slug: 'wclinic-food-allergy-test',
    nameZhTw: '食物過敏檢測 (120項)',
    nameJa: 'フードアレルギー検査 (120項目)',
    nameEn: 'Food Allergy Test (120 items)',
    descriptionZhTw: '食物過敏原檢測·120項IgG抗體',
    priceJpy: 41800,
    category: 'other',
    sortOrder: 179,
  },
  'wclinic-counseling': {
    slug: 'wclinic-counseling',
    nameZhTw: '諮詢',
    nameJa: 'カウンセリング',
    nameEn: 'Consultation',
    descriptionZhTw: '醫師諮詢·初診',
    priceJpy: 1100,
    category: 'other',
    sortOrder: 180,
  },

  // ─── 先端細胞医療（Cell-Medicine × iPeace）咨询服务 ───
  'cell-medicine-initial-consultation': {
    slug: 'cell-medicine-initial-consultation',
    nameZhTw: '先端細胞醫療 - 前期諮詢服務',
    nameJa: '先端細胞医療 - 初期相談サービス',
    nameEn: 'Advanced Cell Medicine - Initial Consultation',
    descriptionZhTw: '病歷翻譯、醫療機構諮詢、自體癌症疫苗/iPS細胞治療方案評估、費用概算',
    priceJpy: 221000,
    category: 'other',
    sortOrder: 150,
  },
  'cell-medicine-remote-consultation': {
    slug: 'cell-medicine-remote-consultation',
    nameZhTw: '先端細胞醫療 - 遠程診斷服務',
    nameJa: '先端細胞医療 - 遠隔診療サービス',
    nameEn: 'Advanced Cell Medicine - Remote Consultation',
    descriptionZhTw: '與專科醫生遠程視頻會診、自體癌症疫苗/iPS細胞治療方案評估、個性化診療計劃',
    priceJpy: 243000,
    category: 'other',
    sortOrder: 151,
  },

  // ─── AC Cell Clinic (ACセルクリニック) 咨询服务 ───
  'ac-plus-initial-consultation': {
    slug: 'ac-plus-initial-consultation',
    nameZhTw: 'AC Cell Clinic - 前期諮詢服務',
    nameJa: 'ACセルクリニック - 初期相談サービス',
    nameEn: 'AC Cell Clinic - Initial Consultation',
    descriptionZhTw: '病歷翻譯、診所諮詢、再生醫療方案評估、費用概算',
    priceJpy: 221000,
    category: 'other',
    sortOrder: 155,
  },
  'ac-plus-remote-consultation': {
    slug: 'ac-plus-remote-consultation',
    nameZhTw: 'AC Cell Clinic - 遠程診斷服務',
    nameJa: 'ACセルクリニック - 遠隔診療サービス',
    nameEn: 'AC Cell Clinic - Remote Consultation',
    descriptionZhTw: '與ACセルクリニック專科醫生遠程視頻會診、再生醫療方案評估、費用概算',
    priceJpy: 243000,
    category: 'other',
    sortOrder: 156,
  },

  // ─── AC Cell Clinic 血液検査 ───
  'ac-plus-initial-blood-test': {
    slug: 'ac-plus-initial-blood-test',
    nameZhTw: '初次驗血檢查',
    nameJa: '初回採血検査',
    nameEn: 'Initial Blood Test',
    descriptionZhTw: '生活習慣病風險篩檢及感染症檢查',
    priceJpy: 33000,
    category: 'other',
    sortOrder: 400,
  },
  'ac-plus-regular-blood-test': {
    slug: 'ac-plus-regular-blood-test',
    nameZhTw: '定期血液檢查',
    nameJa: '定期検査',
    nameEn: 'Regular Blood Test',
    descriptionZhTw: '一般血液檢查（不含感染症篩檢）·建議每年2-4次',
    priceJpy: 22000,
    category: 'other',
    sortOrder: 401,
  },
  'ac-plus-cancer-screening-male': {
    slug: 'ac-plus-cancer-screening-male',
    nameZhTw: '癌症檢查（男性）',
    nameJa: 'がん検査（男性）',
    nameEn: 'Cancer Screening (Male)',
    descriptionZhTw: '腫瘤標記物：CEA、CA19-9、CA72-4、PSA、AFP',
    priceJpy: 33000,
    category: 'other',
    sortOrder: 402,
  },
  'ac-plus-cancer-screening-female': {
    slug: 'ac-plus-cancer-screening-female',
    nameZhTw: '癌症檢查（女性）',
    nameJa: 'がん検査（女性）',
    nameEn: 'Cancer Screening (Female)',
    descriptionZhTw: '腫瘤標記物：CEA、CA19-9、CA125、CA15-3、CA72-4、AFP',
    priceJpy: 33000,
    category: 'other',
    sortOrder: 403,
  },

  // ─── AC Cell Clinic 自己脂肪由来幹細胞 ───
  'ac-plus-stem-cell-3': {
    slug: 'ac-plus-stem-cell-3',
    nameZhTw: '自體脂肪幹細胞（3次療程）',
    nameJa: '自己脂肪由来幹細胞（3回コース）',
    nameEn: 'Adipose Stem Cell Therapy (3 Sessions)',
    descriptionZhTw: '自體脂肪幹細胞療法·3次療程·每次220萬日元',
    priceJpy: 7260000,
    category: 'other',
    sortOrder: 410,
  },
  'ac-plus-stem-cell-6': {
    slug: 'ac-plus-stem-cell-6',
    nameZhTw: '自體脂肪幹細胞（6次療程）',
    nameJa: '自己脂肪由来幹細胞（6回コース）',
    nameEn: 'Adipose Stem Cell Therapy (6 Sessions)',
    descriptionZhTw: '自體脂肪幹細胞療法·6次療程·每次200萬日元',
    priceJpy: 13200000,
    category: 'other',
    sortOrder: 411,
  },
  'ac-plus-stem-cell-10': {
    slug: 'ac-plus-stem-cell-10',
    nameZhTw: '自體脂肪幹細胞（10次療程）',
    nameJa: '自己脂肪由来幹細胞（10回コース）',
    nameEn: 'Adipose Stem Cell Therapy (10 Sessions)',
    descriptionZhTw: '自體脂肪幹細胞療法·10次療程·每次180萬日元',
    priceJpy: 19800000,
    category: 'other',
    sortOrder: 412,
  },

  // ─── AC Cell Clinic NK細胞 ───
  'ac-plus-nk-cell-1': {
    slug: 'ac-plus-nk-cell-1',
    nameZhTw: 'NK細胞療法（1次）',
    nameJa: 'NK細胞（1回）',
    nameEn: 'NK Cell Therapy (1 Session)',
    descriptionZhTw: 'NK自然殺手細胞療法·單次療程',
    priceJpy: 935000,
    category: 'other',
    sortOrder: 415,
  },
  'ac-plus-nk-cell-5': {
    slug: 'ac-plus-nk-cell-5',
    nameZhTw: 'NK細胞療法（5次療程）',
    nameJa: 'NK細胞（5回コース）',
    nameEn: 'NK Cell Therapy (5 Sessions)',
    descriptionZhTw: 'NK自然殺手細胞療法·5次療程·每次80萬日元',
    priceJpy: 4400000,
    category: 'other',
    sortOrder: 416,
  },
  'ac-plus-nk-cell-10': {
    slug: 'ac-plus-nk-cell-10',
    nameZhTw: 'NK細胞療法（10次療程）',
    nameJa: 'NK細胞（10回コース）',
    nameEn: 'NK Cell Therapy (10 Sessions)',
    descriptionZhTw: 'NK自然殺手細胞療法·10次療程·每次77萬日元',
    priceJpy: 8470000,
    category: 'other',
    sortOrder: 417,
  },

  // ─── AC Cell Clinic 血液クレンジング ───
  'ac-plus-blood-purification-1': {
    slug: 'ac-plus-blood-purification-1',
    nameZhTw: '血液淨化療法（1次）',
    nameJa: '血液クレンジング（1回）',
    nameEn: 'Blood Purification (1 Session)',
    descriptionZhTw: 'Leocana濾器血液淨化·單次療程',
    priceJpy: 1210000,
    category: 'other',
    sortOrder: 420,
  },
  'ac-plus-blood-purification-3': {
    slug: 'ac-plus-blood-purification-3',
    nameZhTw: '血液淨化療法（3次療程）',
    nameJa: '血液クレンジング（3回コース）',
    nameEn: 'Blood Purification (3 Sessions)',
    descriptionZhTw: 'Leocana濾器血液淨化·3次療程·每次99萬日元',
    priceJpy: 3267000,
    category: 'other',
    sortOrder: 421,
  },
  'ac-plus-blood-purification-5': {
    slug: 'ac-plus-blood-purification-5',
    nameZhTw: '血液淨化療法（5次療程）',
    nameJa: '血液クレンジング（5回コース）',
    nameEn: 'Blood Purification (5 Sessions)',
    descriptionZhTw: 'Leocana濾器血液淨化·5次療程·每次88萬日元',
    priceJpy: 4840000,
    category: 'other',
    sortOrder: 422,
  },

  // ─── AC Cell Clinic 自己血由来幹細胞上清液 ───
  'ac-plus-autologous-supernatant-1': {
    slug: 'ac-plus-autologous-supernatant-1',
    nameZhTw: '自體血幹細胞上清液（1次）',
    nameJa: '自己血由来幹細胞上清液（1回）',
    nameEn: 'Autologous Blood Stem Cell Supernatant (1 Session)',
    descriptionZhTw: '自體血液幹細胞上清液·2ml·單次療程',
    priceJpy: 550000,
    category: 'other',
    sortOrder: 425,
  },
  'ac-plus-autologous-supernatant-12': {
    slug: 'ac-plus-autologous-supernatant-12',
    nameZhTw: '自體血幹細胞上清液（12次套餐）',
    nameJa: '自己血由来幹細胞上清液（12回セット）',
    nameEn: 'Autologous Blood Stem Cell Supernatant (12 Sessions)',
    descriptionZhTw: '自體血液幹細胞上清液·12次套餐',
    priceJpy: 6600000,
    category: 'other',
    sortOrder: 426,
  },
  'ac-plus-autologous-supernatant-24': {
    slug: 'ac-plus-autologous-supernatant-24',
    nameZhTw: '自體血幹細胞上清液（24次套餐）',
    nameJa: '自己血由来幹細胞上清液（24回セット）',
    nameEn: 'Autologous Blood Stem Cell Supernatant (24 Sessions)',
    descriptionZhTw: '自體血液幹細胞上清液·24次套餐',
    priceJpy: 13200000,
    category: 'other',
    sortOrder: 427,
  },

  // ─── AC Cell Clinic 幹細胞上清液 ───
  'ac-plus-umbilical-supernatant': {
    slug: 'ac-plus-umbilical-supernatant',
    nameZhTw: '臍帶幹細胞上清液（2ml）',
    nameJa: '臍帯幹細胞上清液（2ml）',
    nameEn: 'Umbilical Cord Stem Cell Supernatant (2ml)',
    descriptionZhTw: '臍帶幹細胞上清液·專注皮膚再生及新生血管',
    priceJpy: 220000,
    category: 'other',
    sortOrder: 430,
  },
  'ac-plus-adipose-supernatant': {
    slug: 'ac-plus-adipose-supernatant',
    nameZhTw: '脂肪幹細胞上清液（2ml）',
    nameJa: '脂肪幹細胞上清液（2ml）',
    nameEn: 'Adipose Stem Cell Supernatant (2ml)',
    descriptionZhTw: '脂肪幹細胞上清液·全身性（皮膚、關節、肌肉）',
    priceJpy: 220000,
    category: 'other',
    sortOrder: 431,
  },
  'ac-plus-adipose-umbilical-supernatant': {
    slug: 'ac-plus-adipose-umbilical-supernatant',
    nameZhTw: '脂肪臍帶幹細胞上清液 SPECIAL（4ml）',
    nameJa: '脂肪臍帯幹細胞上清液 SPECIAL（4ml）',
    nameEn: 'Adipose + Umbilical Stem Cell Supernatant SPECIAL (4ml)',
    descriptionZhTw: '脂肪+臍帶幹細胞複合上清液·4ml',
    priceJpy: 440000,
    category: 'other',
    sortOrder: 432,
  },
  'ac-plus-special-mix-supernatant': {
    slug: 'ac-plus-special-mix-supernatant',
    nameZhTw: 'SPECIAL MIX 上清液（4ml）',
    nameJa: 'SPECIAL MIX上清液（4ml）',
    nameEn: 'SPECIAL MIX Supernatant (4ml)',
    descriptionZhTw: '含全種類成長因子的頂級複合上清液·4ml',
    priceJpy: 550000,
    category: 'other',
    sortOrder: 433,
  },

  // ─── AC Cell Clinic 美肌メニュー ───
  'ac-plus-skin-acrs': {
    slug: 'ac-plus-skin-acrs',
    nameZhTw: '美膚 ACRS（自體血細胞因子血清）',
    nameJa: '美肌 ACRS（自己血サイトカインリッチ血清）',
    nameEn: 'Skin Beauty ACRS (Autologous Cytokine-Rich Serum)',
    descriptionZhTw: 'ACRS自體血細胞因子磷脂血清·水光注射/MPGUN',
    priceJpy: 550000,
    category: 'other',
    sortOrder: 440,
  },
  'ac-plus-skin-prp': {
    slug: 'ac-plus-skin-prp',
    nameZhTw: '美膚 PRP（多血小板血漿）',
    nameJa: '美肌 PRP（多血小板血漿）',
    nameEn: 'Skin Beauty PRP (Platelet-Rich Plasma)',
    descriptionZhTw: 'PRP多血小板血漿·水光注射/MPGUN',
    priceJpy: 220000,
    category: 'other',
    sortOrder: 441,
  },
  'ac-plus-skin-special-mix': {
    slug: 'ac-plus-skin-special-mix',
    nameZhTw: '美膚 SPECIAL MIX上清液',
    nameJa: '美肌 SPECIAL MIX上清液',
    nameEn: 'Skin Beauty SPECIAL MIX Supernatant',
    descriptionZhTw: 'SPECIAL MIX上清液·水光注射/MPGUN',
    priceJpy: 605000,
    category: 'other',
    sortOrder: 442,
  },
  'ac-plus-skin-adipose-umbilical': {
    slug: 'ac-plus-skin-adipose-umbilical',
    nameZhTw: '美膚 脂肪臍帶幹細胞上清液',
    nameJa: '美肌 脂肪臍帯幹細胞上清液',
    nameEn: 'Skin Beauty Adipose + Umbilical Supernatant',
    descriptionZhTw: '脂肪臍帶幹細胞上清液·水光注射/MPGUN',
    priceJpy: 495000,
    category: 'other',
    sortOrder: 443,
  },
  'ac-plus-skin-adipose': {
    slug: 'ac-plus-skin-adipose',
    nameZhTw: '美膚 脂肪幹細胞上清液',
    nameJa: '美肌 脂肪幹細胞上清液',
    nameEn: 'Skin Beauty Adipose Supernatant',
    descriptionZhTw: '脂肪幹細胞上清液·水光注射/MPGUN',
    priceJpy: 275000,
    category: 'other',
    sortOrder: 444,
  },
  'ac-plus-skin-umbilical': {
    slug: 'ac-plus-skin-umbilical',
    nameZhTw: '美膚 臍帶幹細胞上清液',
    nameJa: '美肌 臍帯幹細胞上清液',
    nameEn: 'Skin Beauty Umbilical Supernatant',
    descriptionZhTw: '臍帶幹細胞上清液·水光注射/MPGUN',
    priceJpy: 275000,
    category: 'other',
    sortOrder: 445,
  },
  'ac-plus-cellage-3d-mask': {
    slug: 'ac-plus-cellage-3d-mask',
    nameZhTw: 'CELLAGE 3D MASK',
    nameJa: 'CELLAGE 3D MASK',
    nameEn: 'CELLAGE 3D MASK',
    descriptionZhTw: '日本人體脂肪細胞培養萃取液面膜',
    priceJpy: 1980,
    category: 'other',
    sortOrder: 446,
  },

  // ─── AC Cell Clinic 頭皮ケアメニュー ───
  'ac-plus-scalp-acrs': {
    slug: 'ac-plus-scalp-acrs',
    nameZhTw: '頭皮護理 ACRS',
    nameJa: '頭皮ケア ACRS',
    nameEn: 'Scalp Care ACRS',
    descriptionZhTw: 'ACRS自體血細胞因子血清·MPGUN頭皮導入',
    priceJpy: 605000,
    category: 'other',
    sortOrder: 450,
  },
  'ac-plus-scalp-prp': {
    slug: 'ac-plus-scalp-prp',
    nameZhTw: '頭皮護理 PRP',
    nameJa: '頭皮ケア PRP',
    nameEn: 'Scalp Care PRP',
    descriptionZhTw: 'PRP多血小板血漿·MPGUN頭皮導入',
    priceJpy: 275000,
    category: 'other',
    sortOrder: 451,
  },
  'ac-plus-scalp-special-mix': {
    slug: 'ac-plus-scalp-special-mix',
    nameZhTw: '頭皮護理 SPECIAL MIX上清液',
    nameJa: '頭皮ケア SPECIAL MIX上清液',
    nameEn: 'Scalp Care SPECIAL MIX Supernatant',
    descriptionZhTw: 'SPECIAL MIX上清液·MPGUN頭皮導入',
    priceJpy: 660000,
    category: 'other',
    sortOrder: 452,
  },
  'ac-plus-scalp-adipose-umbilical': {
    slug: 'ac-plus-scalp-adipose-umbilical',
    nameZhTw: '頭皮護理 脂肪臍帶幹細胞上清液',
    nameJa: '頭皮ケア 脂肪臍帯幹細胞上清液',
    nameEn: 'Scalp Care Adipose + Umbilical Supernatant',
    descriptionZhTw: '脂肪臍帶幹細胞上清液·MPGUN頭皮導入',
    priceJpy: 550000,
    category: 'other',
    sortOrder: 453,
  },
  'ac-plus-scalp-adipose': {
    slug: 'ac-plus-scalp-adipose',
    nameZhTw: '頭皮護理 脂肪幹細胞上清液',
    nameJa: '頭皮ケア 脂肪幹細胞上清液',
    nameEn: 'Scalp Care Adipose Supernatant',
    descriptionZhTw: '脂肪幹細胞上清液·MPGUN頭皮導入',
    priceJpy: 330000,
    category: 'other',
    sortOrder: 454,
  },
  'ac-plus-scalp-umbilical': {
    slug: 'ac-plus-scalp-umbilical',
    nameZhTw: '頭皮護理 臍帶幹細胞上清液',
    nameJa: '頭皮ケア 臍帯幹細胞上清液',
    nameEn: 'Scalp Care Umbilical Supernatant',
    descriptionZhTw: '臍帶幹細胞上清液·MPGUN頭皮導入',
    priceJpy: 330000,
    category: 'other',
    sortOrder: 455,
  },

  // ─── AC Cell Clinic 膝メニュー ───
  'ac-plus-knee-acrs-both': {
    slug: 'ac-plus-knee-acrs-both',
    nameZhTw: '膝關節 ACRS（雙膝）',
    nameJa: '膝 ACRS（両膝）',
    nameEn: 'Knee ACRS (Both Knees)',
    descriptionZhTw: 'ACRS自體血細胞因子血清·雙膝關節注射',
    priceJpy: 1100000,
    category: 'other',
    sortOrder: 460,
  },
  'ac-plus-knee-prp-both': {
    slug: 'ac-plus-knee-prp-both',
    nameZhTw: '膝關節 PRP（雙膝）',
    nameJa: '膝 PRP（両膝）',
    nameEn: 'Knee PRP (Both Knees)',
    descriptionZhTw: 'PRP多血小板血漿·雙膝關節注射',
    priceJpy: 880000,
    category: 'other',
    sortOrder: 461,
  },
  'ac-plus-knee-prp-single': {
    slug: 'ac-plus-knee-prp-single',
    nameZhTw: '膝關節 PRP（單膝）',
    nameJa: '膝 PRP（片膝）',
    nameEn: 'Knee PRP (Single Knee)',
    descriptionZhTw: 'PRP多血小板血漿·單膝關節注射',
    priceJpy: 550000,
    category: 'other',
    sortOrder: 462,
  },

  // ─── AC Cell Clinic 笑気麻酔 ───
  'ac-plus-nitrous-oxide': {
    slug: 'ac-plus-nitrous-oxide',
    nameZhTw: '笑氣麻醉（30分鐘）',
    nameJa: '笑気麻酔（30分）',
    nameEn: 'Nitrous Oxide Anesthesia (30 min)',
    descriptionZhTw: '笑氣麻醉·30分鐘',
    priceJpy: 33000,
    category: 'other',
    sortOrder: 465,
  },

  // ─── AC Cell Clinic プリペイド会員 ───
  'ac-plus-prepaid-platina': {
    slug: 'ac-plus-prepaid-platina',
    nameZhTw: '點滴會員 PLATINA（全品9折）',
    nameJa: 'プリペイド点滴会員 PLATINA（10%OFF）',
    nameEn: 'IV Drip Membership PLATINA (10% OFF)',
    descriptionZhTw: '預付點滴注射會員·全品項9折·1年有效',
    priceJpy: 605000,
    category: 'other',
    sortOrder: 468,
  },
  'ac-plus-prepaid-diamond': {
    slug: 'ac-plus-prepaid-diamond',
    nameZhTw: '點滴會員 DIAMOND（全品8折）',
    nameJa: 'プリペイド点滴会員 DIAMOND（20%OFF）',
    nameEn: 'IV Drip Membership DIAMOND (20% OFF)',
    descriptionZhTw: '預付點滴注射會員·全品項8折·1年有效',
    priceJpy: 1100000,
    category: 'other',
    sortOrder: 469,
  },

  // ─── AC Cell Clinic 点滴 SPECIAL ───
  'ac-plus-hermes-drip': {
    slug: 'ac-plus-hermes-drip',
    nameZhTw: '愛馬仕點滴',
    nameJa: 'Hermes点滴',
    nameEn: 'Hermes Drip',
    descriptionZhTw: '氨基酸·維生素B群·維C·α-硫辛酸·穀胱甘肽·氨甲環酸·左旋肉鹼·45分鐘',
    priceJpy: 66000,
    category: 'other',
    sortOrder: 470,
  },

  // ─── AC Cell Clinic 点滴 NMN ───
  'ac-plus-nmn-150': {
    slug: 'ac-plus-nmn-150',
    nameZhTw: 'NMN點滴 150mg',
    nameJa: 'NMN点滴 150mg',
    nameEn: 'NMN IV Drip 150mg',
    descriptionZhTw: 'NMN抗衰點滴·150mg·45分鐘',
    priceJpy: 88000,
    category: 'other',
    sortOrder: 472,
  },
  'ac-plus-nmn-500': {
    slug: 'ac-plus-nmn-500',
    nameZhTw: 'NMN點滴 500mg',
    nameJa: 'NMN点滴 500mg',
    nameEn: 'NMN IV Drip 500mg',
    descriptionZhTw: 'NMN抗衰點滴·500mg·45分鐘',
    priceJpy: 275000,
    category: 'other',
    sortOrder: 473,
  },

  // ─── AC Cell Clinic 高濃度ビタミンC点滴 ───
  'ac-plus-vitc-1200-us': {
    slug: 'ac-plus-vitc-1200-us',
    nameZhTw: '高濃度維C 1200mg（美國製）',
    nameJa: '高濃度ビタミンC 1200mg（アメリカ製）',
    nameEn: 'High-Dose Vitamin C 1200mg (US)',
    descriptionZhTw: '高濃度維生素C點滴·1200mg·美國製·30分鐘',
    priceJpy: 33000,
    category: 'other',
    sortOrder: 475,
  },
  'ac-plus-vitc-1200-jp': {
    slug: 'ac-plus-vitc-1200-jp',
    nameZhTw: '高濃度維C 1200mg（日本製）',
    nameJa: '高濃度ビタミンC 1200mg（日本製）',
    nameEn: 'High-Dose Vitamin C 1200mg (Japan)',
    descriptionZhTw: '高濃度維生素C點滴·1200mg·日本製·30分鐘',
    priceJpy: 38500,
    category: 'other',
    sortOrder: 476,
  },
  'ac-plus-vitc-2500-us': {
    slug: 'ac-plus-vitc-2500-us',
    nameZhTw: '超高濃度維C 2500mg（美國製）',
    nameJa: '超高濃度ビタミンC 2500mg（アメリカ製）',
    nameEn: 'Ultra High-Dose Vitamin C 2500mg (US)',
    descriptionZhTw: '超高濃度維生素C點滴·2500mg·美國製·45分鐘',
    priceJpy: 55000,
    category: 'other',
    sortOrder: 477,
  },
  'ac-plus-vitc-2500-jp': {
    slug: 'ac-plus-vitc-2500-jp',
    nameZhTw: '超高濃度維C 2500mg（日本製）',
    nameJa: '超高濃度ビタミンC 2500mg（日本製）',
    nameEn: 'Ultra High-Dose Vitamin C 2500mg (Japan)',
    descriptionZhTw: '超高濃度維生素C點滴·2500mg·日本製·45分鐘',
    priceJpy: 66000,
    category: 'other',
    sortOrder: 478,
  },

  // ─── AC Cell Clinic 疲労・風邪 点滴 ───
  'ac-plus-cold-mild': {
    slug: 'ac-plus-cold-mild',
    nameZhTw: '風寒前兆點滴',
    nameJa: '風邪気味点滴',
    nameEn: 'Mild Cold IV Drip',
    descriptionZhTw: '感冒初期症狀緩解·15分鐘',
    priceJpy: 11000,
    category: 'other',
    sortOrder: 480,
  },
  'ac-plus-fatigue-recovery': {
    slug: 'ac-plus-fatigue-recovery',
    nameZhTw: '疲勞恢復點滴',
    nameJa: '疲労回復点滴',
    nameEn: 'Fatigue Recovery IV Drip',
    descriptionZhTw: '疲勞恢復·15分鐘',
    priceJpy: 11000,
    category: 'other',
    sortOrder: 481,
  },
  'ac-plus-fatigue-detox': {
    slug: 'ac-plus-fatigue-detox',
    nameZhTw: '疲勞恢復排毒點滴',
    nameJa: '疲労回復デトックス点滴',
    nameEn: 'Fatigue Recovery Detox IV Drip',
    descriptionZhTw: '疲勞恢復+排毒·15分鐘',
    priceJpy: 14300,
    category: 'other',
    sortOrder: 482,
  },
  'ac-plus-cold-work': {
    slug: 'ac-plus-cold-work',
    nameZhTw: '感冒工作點滴',
    nameJa: '風邪なのに仕事点滴',
    nameEn: 'Cold + Work IV Drip',
    descriptionZhTw: '感冒了還要工作·快速緩解·30分鐘',
    priceJpy: 16500,
    category: 'other',
    sortOrder: 483,
  },
  'ac-plus-fatigue-special': {
    slug: 'ac-plus-fatigue-special',
    nameZhTw: '特別疲勞恢復點滴',
    nameJa: '疲労回復スペシャル点滴',
    nameEn: 'Fatigue Recovery Special IV Drip',
    descriptionZhTw: '高效疲勞恢復·30分鐘',
    priceJpy: 22000,
    category: 'other',
    sortOrder: 484,
  },

  // ─── AC Cell Clinic 肝臓 点滴 ───
  'ac-plus-hangover': {
    slug: 'ac-plus-hangover',
    nameZhTw: '宿醉點滴',
    nameJa: '二日酔い点滴',
    nameEn: 'Hangover IV Drip',
    descriptionZhTw: '宿醉緩解·15分鐘',
    priceJpy: 11000,
    category: 'other',
    sortOrder: 490,
  },
  'ac-plus-liver-care': {
    slug: 'ac-plus-liver-care',
    nameZhTw: '護肝點滴',
    nameJa: '肝臓を大切に点滴',
    nameEn: 'Liver Care IV Drip',
    descriptionZhTw: '肝臟保養·15分鐘',
    priceJpy: 11000,
    category: 'other',
    sortOrder: 491,
  },
  'ac-plus-liver-limit': {
    slug: 'ac-plus-liver-limit',
    nameZhTw: '肝臟極限點滴',
    nameJa: 'もう限界点滴',
    nameEn: 'Liver Limit IV Drip',
    descriptionZhTw: '肝臟達到極限·深層修復·30分鐘',
    priceJpy: 16500,
    category: 'other',
    sortOrder: 492,
  },
  'ac-plus-liver-drinking': {
    slug: 'ac-plus-liver-drinking',
    nameZhTw: '飲酒應酬點滴',
    nameJa: '今夜も飲み会点滴',
    nameEn: 'Drinking Party IV Drip',
    descriptionZhTw: '今晚又有飲酒聚會·預防護肝·30分鐘',
    priceJpy: 16500,
    category: 'other',
    sortOrder: 493,
  },
  'ac-plus-liver-protect': {
    slug: 'ac-plus-liver-protect',
    nameZhTw: '保護肝臟點滴',
    nameJa: '肝臓を守ろう点滴',
    nameEn: 'Liver Protection IV Drip',
    descriptionZhTw: '肝臟保護·30分鐘',
    priceJpy: 16500,
    category: 'other',
    sortOrder: 494,
  },
  'ac-plus-liver-boost': {
    slug: 'ac-plus-liver-boost',
    nameZhTw: '肝臟注入能量點滴',
    nameJa: '肝臓に元気注入点滴',
    nameEn: 'Liver Boost IV Drip',
    descriptionZhTw: '為肝臟注入能量·30分鐘',
    priceJpy: 16500,
    category: 'other',
    sortOrder: 495,
  },
  'ac-plus-liver-special': {
    slug: 'ac-plus-liver-special',
    nameZhTw: '肝臟特別點滴',
    nameJa: '肝臓スペシャル点滴',
    nameEn: 'Liver Special IV Drip',
    descriptionZhTw: '肝臟深層修復·頂級配方·40分鐘',
    priceJpy: 22000,
    category: 'other',
    sortOrder: 496,
  },

  // ─── AC Cell Clinic 美肌 点滴 ───
  'ac-plus-whitening-drip': {
    slug: 'ac-plus-whitening-drip',
    nameZhTw: '美白白玉點滴',
    nameJa: '美白・白玉点滴',
    nameEn: 'Whitening IV Drip',
    descriptionZhTw: '穀胱甘肽美白點滴·15分鐘',
    priceJpy: 11000,
    category: 'other',
    sortOrder: 500,
  },
  'ac-plus-aging-care-drip': {
    slug: 'ac-plus-aging-care-drip',
    nameZhTw: '抗衰老點滴',
    nameJa: 'エイジングケア点滴',
    nameEn: 'Anti-Aging IV Drip',
    descriptionZhTw: '抗衰老護膚點滴·40分鐘',
    priceJpy: 22000,
    category: 'other',
    sortOrder: 501,
  },
  'ac-plus-skin-quality-drip': {
    slug: 'ac-plus-skin-quality-drip',
    nameZhTw: '膚質改善點滴',
    nameJa: '肌質改善点滴',
    nameEn: 'Skin Quality IV Drip',
    descriptionZhTw: '改善膚質·30分鐘',
    priceJpy: 22000,
    category: 'other',
    sortOrder: 502,
  },
  'ac-plus-skin-special-drip': {
    slug: 'ac-plus-skin-special-drip',
    nameZhTw: '特別美膚點滴',
    nameJa: '美肌スペシャル点滴',
    nameEn: 'Skin Beauty Special IV Drip',
    descriptionZhTw: '頂級美膚配方·40分鐘',
    priceJpy: 22000,
    category: 'other',
    sortOrder: 503,
  },

  // ─── AC Cell Clinic ダイエット 点滴 ───
  'ac-plus-diet-drip': {
    slug: 'ac-plus-diet-drip',
    nameZhTw: '減肥點滴',
    nameJa: 'ダイエット点滴',
    nameEn: 'Diet IV Drip',
    descriptionZhTw: '減肥代謝促進·15分鐘',
    priceJpy: 11000,
    category: 'other',
    sortOrder: 506,
  },
  'ac-plus-diet-special-drip': {
    slug: 'ac-plus-diet-special-drip',
    nameZhTw: '特別減肥點滴',
    nameJa: 'ダイエットスペシャル点滴',
    nameEn: 'Diet Special IV Drip',
    descriptionZhTw: '高效減肥代謝促進·25分鐘',
    priceJpy: 22000,
    category: 'other',
    sortOrder: 507,
  },

  // ─── AC Cell Clinic 花粉症 点滴 ───
  'ac-plus-hay-fever-drip': {
    slug: 'ac-plus-hay-fever-drip',
    nameZhTw: '花粉症點滴',
    nameJa: '花粉症点滴',
    nameEn: 'Hay Fever IV Drip',
    descriptionZhTw: '花粉症緩解·15分鐘',
    priceJpy: 11000,
    category: 'other',
    sortOrder: 510,
  },
  'ac-plus-hay-fever-special-drip': {
    slug: 'ac-plus-hay-fever-special-drip',
    nameZhTw: '花粉症特別點滴',
    nameJa: '花粉症スペシャル点滴',
    nameEn: 'Hay Fever Special IV Drip',
    descriptionZhTw: '花粉症強效緩解·30分鐘',
    priceJpy: 16500,
    category: 'other',
    sortOrder: 511,
  },

  // ─── AC Cell Clinic プラセンタ・注射 ───
  'ac-plus-placenta-2a': {
    slug: 'ac-plus-placenta-2a',
    nameZhTw: '胎盤素注射 2A',
    nameJa: 'プラセンタ 2A',
    nameEn: 'Placenta Injection 2A',
    descriptionZhTw: '胎盤素注射·Laennec/Melsmon可選',
    priceJpy: 5500,
    category: 'other',
    sortOrder: 515,
  },
  'ac-plus-fatigue-injection': {
    slug: 'ac-plus-fatigue-injection',
    nameZhTw: '疲勞恢復注射（20ml）',
    nameJa: '疲労回復注射（20ml）',
    nameEn: 'Fatigue Recovery Injection (20ml)',
    descriptionZhTw: '快速疲勞恢復注射·20ml',
    priceJpy: 5500,
    category: 'other',
    sortOrder: 518,
  },
  'ac-plus-vitamin-fatigue-injection': {
    slug: 'ac-plus-vitamin-fatigue-injection',
    nameZhTw: '維生素疲勞恢復注射（25ml）',
    nameJa: 'ビタミン疲労回復注射（25ml）',
    nameEn: 'Vitamin Fatigue Recovery Injection (25ml)',
    descriptionZhTw: '維生素+疲勞恢復注射·25ml',
    priceJpy: 8800,
    category: 'other',
    sortOrder: 519,
  },
  'ac-plus-vitamin-injection': {
    slug: 'ac-plus-vitamin-injection',
    nameZhTw: '維生素注射（20ml）',
    nameJa: 'ビタミン注射（20ml）',
    nameEn: 'Vitamin Injection (20ml)',
    descriptionZhTw: '維生素補充注射·20ml',
    priceJpy: 5500,
    category: 'other',
    sortOrder: 520,
  },
  'ac-plus-drinking-party-injection': {
    slug: 'ac-plus-drinking-party-injection',
    nameZhTw: '聚會注射（20ml）',
    nameJa: '飲み会注射（20ml）',
    nameEn: 'Drinking Party Injection (20ml)',
    descriptionZhTw: '飲酒聚會前後護肝注射·20ml',
    priceJpy: 5500,
    category: 'other',
    sortOrder: 521,
  },

  // ─── 大阪重粒子線中心 咨询服务 ───
  'osaka-himak-initial-consultation': {
    slug: 'osaka-himak-initial-consultation',
    nameZhTw: '大阪重粒子線中心 - 前期諮詢服務',
    nameJa: '大阪重粒子線センター - 初期相談サービス',
    nameEn: 'Osaka HIMAK - Initial Consultation',
    descriptionZhTw: '病歷資料翻譯、重粒子線治療適應性評估、治療計劃初步討論、費用概算',
    priceJpy: 221000,
    category: 'cancer_treatment',
    sortOrder: 157,
  },
  'osaka-himak-remote-consultation': {
    slug: 'osaka-himak-remote-consultation',
    nameZhTw: '大阪重粒子線中心 - 遠程會診服務',
    nameJa: '大阪重粒子線センター - 遠隔診療サービス',
    nameEn: 'Osaka HIMAK - Remote Consultation',
    descriptionZhTw: '與重粒子線治療專家遠程視頻會診、討論治療適應性與方案、費用詳細說明',
    priceJpy: 243000,
    category: 'cancer_treatment',
    sortOrder: 158,
  },

  // ─── IGTクリニック 咨询服务 ───
  'igtc-initial-consultation': {
    slug: 'igtc-initial-consultation',
    nameZhTw: 'IGT診所 - 前期諮詢服務',
    nameJa: 'IGTクリニック - 初期相談サービス',
    nameEn: 'IGT Clinic - Initial Consultation',
    descriptionZhTw: '病歷翻譯、IGT診所諮詢、血管內治療可行性評估、費用概算',
    priceJpy: 221000,
    category: 'cancer_treatment',
    sortOrder: 115,
  },
  'igtc-remote-consultation': {
    slug: 'igtc-remote-consultation',
    nameZhTw: 'IGT診所 - 遠程會診服務',
    nameJa: 'IGTクリニック - 遠隔診療サービス',
    nameEn: 'IGT Clinic - Remote Consultation',
    descriptionZhTw: '與IGT診所專科醫生遠程視頻會診、血管內治療方案制定、費用概算',
    priceJpy: 243000,
    category: 'cancer_treatment',
    sortOrder: 116,
  },

  // ─── IGT 诊所 治疗套餐 ───
  // 血管内治疗核心套餐
  'igtc-standard-initial': {
    slug: 'igtc-standard-initial',
    nameZhTw: 'IGT診所 - 標準治療套餐（1泊2日·初回）',
    nameJa: 'IGTクリニック - 標準治療コース（1泊2日·初回）',
    nameEn: 'IGT Clinic - Standard Treatment Course (2D/1N, Initial)',
    descriptionZhTw: '血管內治療標準套餐·含培養上清液10cc·1晚2天住院',
    priceJpy: 2800000,
    category: 'cancer_treatment',
    sortOrder: 117,
  },
  'igtc-standard-subsequent': {
    slug: 'igtc-standard-subsequent',
    nameZhTw: 'IGT診所 - 標準治療套餐（1泊2日·2回目以降）',
    nameJa: 'IGTクリニック - 標準治療コース（1泊2日·2回目以降）',
    nameEn: 'IGT Clinic - Standard Treatment Course (2D/1N, Follow-up)',
    descriptionZhTw: '血管內治療標準套餐·含培養上清液10cc·1晚2天住院·第2次及之後',
    priceJpy: 2700000,
    category: 'cancer_treatment',
    sortOrder: 118,
  },
  'igtc-standard-outpatient': {
    slug: 'igtc-standard-outpatient',
    nameZhTw: 'IGT診所 - 標準治療套餐（1泊2日·外來済）',
    nameJa: 'IGTクリニック - 標準治療コース（1泊2日·外来済）',
    nameEn: 'IGT Clinic - Standard Treatment Course (2D/1N, Post-Outpatient)',
    descriptionZhTw: '血管內治療標準套餐·含培養上清液10cc·1晚2天住院·已完成外來診察',
    priceJpy: 2350000,
    category: 'cancer_treatment',
    sortOrder: 119,
  },
  'igtc-hyperthermia-hydrogen': {
    slug: 'igtc-hyperthermia-hydrogen',
    nameZhTw: 'IGT診所 - 溫熱治療（併用水素）',
    nameJa: 'IGTクリニック - 温熱治療（水素併用）',
    nameEn: 'IGT Clinic - Hyperthermia with Hydrogen',
    descriptionZhTw: '溫熱治療·併用水素療法·單次療程',
    priceJpy: 38500,
    category: 'cancer_treatment',
    sortOrder: 120,
  },

  // 自家癌症疫苗
  'igtc-cancer-vaccine-1': {
    slug: 'igtc-cancer-vaccine-1',
    nameZhTw: 'IGT診所 - 自家癌症疫苗（1回套餐）',
    nameJa: 'IGTクリニック - 自家がんワクチン（1回コース）',
    nameEn: 'IGT Clinic - Autologous Cancer Vaccine (1 Dose)',
    descriptionZhTw: '個人化癌症疫苗療法·1次療程',
    priceJpy: 900000,
    category: 'cancer_treatment',
    sortOrder: 121,
  },
  'igtc-cancer-vaccine-2': {
    slug: 'igtc-cancer-vaccine-2',
    nameZhTw: 'IGT診所 - 自家癌症疫苗（2回套餐）',
    nameJa: 'IGTクリニック - 自家がんワクチン（2回コース）',
    nameEn: 'IGT Clinic - Autologous Cancer Vaccine (2 Doses)',
    descriptionZhTw: '個人化癌症疫苗療法·2次療程',
    priceJpy: 1766000,
    category: 'cancer_treatment',
    sortOrder: 122,
  },
  'igtc-cancer-vaccine-3': {
    slug: 'igtc-cancer-vaccine-3',
    nameZhTw: 'IGT診所 - 自家癌症疫苗（3回套餐）',
    nameJa: 'IGTクリニック - 自家がんワクチン（3回コース）',
    nameEn: 'IGT Clinic - Autologous Cancer Vaccine (3 Doses)',
    descriptionZhTw: '個人化癌症疫苗療法·3次療程',
    priceJpy: 2701000,
    category: 'cancer_treatment',
    sortOrder: 123,
  },

  // 免疫细胞疗法
  'igtc-immune-iv-1': {
    slug: 'igtc-immune-iv-1',
    nameZhTw: 'IGT診所 - 免疫細胞療法（靜注·1回）',
    nameJa: 'IGTクリニック - 免疫細胞療法（静注·1回）',
    nameEn: 'IGT Clinic - Immune Cell Therapy IV (1 Session)',
    descriptionZhTw: 'αβT細胞靜脈注射療法·1次療程',
    priceJpy: 655000,
    category: 'cancer_treatment',
    sortOrder: 124,
  },
  'igtc-immune-iv-6': {
    slug: 'igtc-immune-iv-6',
    nameZhTw: 'IGT診所 - 免疫細胞療法（靜注·6回套餐）',
    nameJa: 'IGTクリニック - 免疫細胞療法（静注·6回）',
    nameEn: 'IGT Clinic - Immune Cell Therapy IV (6 Sessions)',
    descriptionZhTw: 'αβT細胞靜脈注射療法·6次療程',
    priceJpy: 3240000,
    category: 'cancer_treatment',
    sortOrder: 125,
  },

  // 干细胞治疗
  'igtc-stem-cell-4': {
    slug: 'igtc-stem-cell-4',
    nameZhTw: 'IGT診所 - 幹細胞治療（4回套餐）',
    nameJa: 'IGTクリニック - 幹細胞治療（4回）',
    nameEn: 'IGT Clinic - Stem Cell Therapy (4 Sessions)',
    descriptionZhTw: '幹細胞治療·4次完整療程',
    priceJpy: 11000000,
    category: 'cancer_treatment',
    sortOrder: 126,
  },

  // CTC 检查
  'igtc-ctc-onconomics-plus': {
    slug: 'igtc-ctc-onconomics-plus',
    nameZhTw: 'IGT診所 - CTC檢查（Onconomics Plus）',
    nameJa: 'IGTクリニック - CTC検査（Onconomics Plus）',
    nameEn: 'IGT Clinic - CTC Test (Onconomics Plus)',
    descriptionZhTw: '循環腫瘤細胞檢測·Onconomics Plus 完整版',
    priceJpy: 902000,
    category: 'health_checkup',
    sortOrder: 127,
  },
  'igtc-ctc-onconomics': {
    slug: 'igtc-ctc-onconomics',
    nameZhTw: 'IGT診所 - CTC檢查（Onconomics）',
    nameJa: 'IGTクリニック - CTC検査（Onconomics）',
    nameEn: 'IGT Clinic - CTC Test (Onconomics)',
    descriptionZhTw: '循環腫瘤細胞檢測·Onconomics 標準版',
    priceJpy: 825000,
    category: 'health_checkup',
    sortOrder: 128,
  },
  'igtc-ctc-oncocount': {
    slug: 'igtc-ctc-oncocount',
    nameZhTw: 'IGT診所 - CTC檢查（Oncocount）',
    nameJa: 'IGTクリニック - CTC検査（Oncocount）',
    nameEn: 'IGT Clinic - CTC Test (Oncocount)',
    descriptionZhTw: '循環腫瘤細胞檢測·Oncocount 計數版',
    priceJpy: 269000,
    category: 'health_checkup',
    sortOrder: 129,
  },
  'igtc-ctc-oncotrace': {
    slug: 'igtc-ctc-oncotrace',
    nameZhTw: 'IGT診所 - CTC檢查（Oncotrace）',
    nameJa: 'IGTクリニック - CTC検査（Oncotrace）',
    nameEn: 'IGT Clinic - CTC Test (Oncotrace)',
    descriptionZhTw: '循環腫瘤細胞檢測·Oncotrace 追蹤版',
    priceJpy: 330000,
    category: 'health_checkup',
    sortOrder: 130,
  },

  // 特殊癌症检诊
  'igtc-cancer-screening-ctc': {
    slug: 'igtc-cancer-screening-ctc',
    nameZhTw: 'IGT診所 - 特殊癌症檢診（含CTC）',
    nameJa: 'IGTクリニック - 特殊がん検診（CTC付き）',
    nameEn: 'IGT Clinic - Special Cancer Screening (with CTC)',
    descriptionZhTw: '特殊癌症綜合檢診·含CTC(Oncocount)檢測',
    priceJpy: 528000,
    category: 'health_checkup',
    sortOrder: 131,
  },
  'igtc-cancer-screening': {
    slug: 'igtc-cancer-screening',
    nameZhTw: 'IGT診所 - 特殊癌症檢診（不含CTC）',
    nameJa: 'IGTクリニック - 特殊がん検診（CTCなし）',
    nameEn: 'IGT Clinic - Special Cancer Screening (without CTC)',
    descriptionZhTw: '特殊癌症綜合檢診·不含CTC檢測',
    priceJpy: 440000,
    category: 'health_checkup',
    sortOrder: 132,
  },

  // ─── HELENE 干细胞诊所 治疗套餐 ───
  // 注意：以下价格均为含税价格（税別价格 × 1.1）
  'helene-msc-iv-grade-b-minus': {
    slug: 'helene-msc-iv-grade-b-minus',
    nameZhTw: 'MSC幹細胞 靜脈/皮下 Grade B-（1億個）',
    nameJa: 'MSC幹細胞 静脈/皮下 Grade B-（1億個）',
    nameEn: 'MSC Stem Cell IV/SC Grade B- (100M cells)',
    descriptionZhTw: '間葉系幹細胞靜脈注射或皮下注射·1億個細胞·基礎療程',
    priceJpy: 1452000,
    category: 'other',
    sortOrder: 160,
  },
  'helene-msc-iv-grade-b': {
    slug: 'helene-msc-iv-grade-b',
    nameZhTw: 'MSC幹細胞 靜脈/皮下 Grade B（4億個）',
    nameJa: 'MSC幹細胞 静脈/皮下 Grade B（4億個）',
    nameEn: 'MSC Stem Cell IV/SC Grade B (400M cells)',
    descriptionZhTw: '間葉系幹細胞靜脈注射或皮下注射·4億個細胞·標準療程',
    priceJpy: 2178000,
    category: 'other',
    sortOrder: 161,
  },
  'helene-msc-iv-grade-b-plus': {
    slug: 'helene-msc-iv-grade-b-plus',
    nameZhTw: 'MSC幹細胞 靜脈/皮下 Grade B+（7億個）',
    nameJa: 'MSC幹細胞 静脈/皮下 Grade B+（7億個）',
    nameEn: 'MSC Stem Cell IV/SC Grade B+ (700M cells)',
    descriptionZhTw: '間葉系幹細胞靜脈注射或皮下注射·7億個細胞·增強療程',
    priceJpy: 3630000,
    category: 'other',
    sortOrder: 162,
  },
  'helene-msc-iv-grade-a-minus': {
    slug: 'helene-msc-iv-grade-a-minus',
    nameZhTw: 'MSC幹細胞 靜脈/皮下 Grade A-（10億個）',
    nameJa: 'MSC幹細胞 静脈/皮下 Grade A-（10億個）',
    nameEn: 'MSC Stem Cell IV/SC Grade A- (1B cells)',
    descriptionZhTw: '間葉系幹細胞靜脈注射或皮下注射·10億個細胞·高級療程',
    priceJpy: 4840000,
    category: 'other',
    sortOrder: 163,
  },
  'helene-msc-iv-grade-a': {
    slug: 'helene-msc-iv-grade-a',
    nameZhTw: 'MSC幹細胞 靜脈/皮下 Grade A（22.5億個）',
    nameJa: 'MSC幹細胞 静脈/皮下 Grade A（22.5億個）',
    nameEn: 'MSC Stem Cell IV/SC Grade A (2.25B cells)',
    descriptionZhTw: '間葉系幹細胞靜脈注射或皮下注射·22.5億個細胞·頂級療程',
    priceJpy: 6050000,
    category: 'other',
    sortOrder: 164,
  },
  'helene-msc-knee-single': {
    slug: 'helene-msc-knee-single',
    nameZhTw: 'MSC幹細胞 膝關節注射（單膝）',
    nameJa: 'MSC幹細胞 膝関節内注射（片膝）',
    nameEn: 'MSC Stem Cell Knee Injection (Single)',
    descriptionZhTw: '間葉系幹細胞膝關節內注射·1億個細胞·單膝治療',
    priceJpy: 1185800,
    category: 'other',
    sortOrder: 165,
  },
  'helene-msc-knee-both': {
    slug: 'helene-msc-knee-both',
    nameZhTw: 'MSC幹細胞 膝關節注射（雙膝）',
    nameJa: 'MSC幹細胞 膝関節内注射（両膝）',
    nameEn: 'MSC Stem Cell Knee Injection (Both)',
    descriptionZhTw: '間葉系幹細胞膝關節內注射·2億個細胞·雙膝治療',
    priceJpy: 1633500,
    category: 'other',
    sortOrder: 166,
  },
  'helene-msc-periodontal-single': {
    slug: 'helene-msc-periodontal-single',
    nameZhTw: 'MSC幹細胞 牙周組織注射（單顎）',
    nameJa: 'MSC幹細胞 歯周組織内注射（上顎or下顎）',
    nameEn: 'MSC Stem Cell Periodontal (Single Jaw)',
    descriptionZhTw: '間葉系幹細胞牙周組織內注射·1億個細胞·上顎或下顎',
    priceJpy: 1185800,
    category: 'other',
    sortOrder: 167,
  },
  'helene-msc-periodontal-both': {
    slug: 'helene-msc-periodontal-both',
    nameZhTw: 'MSC幹細胞 牙周組織注射（雙顎）',
    nameJa: 'MSC幹細胞 歯周組織内注射（上下顎）',
    nameEn: 'MSC Stem Cell Periodontal (Both Jaws)',
    descriptionZhTw: '間葉系幹細胞牙周組織內注射·2億個細胞·上下顎',
    priceJpy: 1633500,
    category: 'other',
    sortOrder: 168,
  },
  'helene-msc-hair': {
    slug: 'helene-msc-hair',
    nameZhTw: 'MSC幹細胞 脫髮部位注射 Grade B',
    nameJa: 'MSC幹細胞 脱毛部位注射 Grade B',
    nameEn: 'MSC Stem Cell Hair Loss Treatment Grade B',
    descriptionZhTw: '間葉系幹細胞脫髮部位注射·10億個細胞·毛髮再生療程',
    priceJpy: 3025000,
    category: 'other',
    sortOrder: 169,
  },
  'helene-exosome-topical': {
    slug: 'helene-exosome-topical',
    nameZhTw: '自體外泌體 外用塗抹（6個月份）',
    nameJa: '自己エクソソーム 外用塗布（6ヶ月分）',
    nameEn: 'Autologous Exosome Topical (6 Months)',
    descriptionZhTw: '自體培養外泌體·外用塗抹·6個月療程份量',
    priceJpy: 2178000,
    category: 'other',
    sortOrder: 170,
  },
  'helene-exosome-injection': {
    slug: 'helene-exosome-injection',
    nameZhTw: '自體外泌體 自我注射（1個月份）',
    nameJa: '自己エクソソーム セルフ注射（1ヶ月分）',
    nameEn: 'Autologous Exosome Self-Injection (1 Month)',
    descriptionZhTw: '自體培養外泌體·自我注射·1個月療程份量',
    priceJpy: 550000,
    category: 'other',
    sortOrder: 171,
  },
  'helene-nk-50': {
    slug: 'helene-nk-50',
    nameZhTw: 'NK細胞 靜脈投與（50億個）',
    nameJa: 'NK細胞 静脈投与（50億個）',
    nameEn: 'NK Cell IV Therapy (5B cells)',
    descriptionZhTw: 'NK自然殺手細胞靜脈投與·50億個細胞·免疫增強療程',
    priceJpy: 550000,
    category: 'other',
    sortOrder: 172,
  },
  'helene-nk-100': {
    slug: 'helene-nk-100',
    nameZhTw: 'NK細胞 靜脈投與（100億個）',
    nameJa: 'NK細胞 静脈投与（100億個）',
    nameEn: 'NK Cell IV Therapy (10B cells)',
    descriptionZhTw: 'NK自然殺手細胞靜脈投與·100億個細胞·高劑量免疫療程',
    priceJpy: 660000,
    category: 'other',
    sortOrder: 173,
  },
  'helene-blood-purification': {
    slug: 'helene-blood-purification',
    nameZhTw: '血液淨化療法',
    nameJa: '血液浄化療法',
    nameEn: 'Blood Purification Therapy',
    descriptionZhTw: '血液淨化·排除體內毒素·改善血液循環',
    priceJpy: 880000,
    category: 'other',
    sortOrder: 174,
  },

  // ─── OICI（大阪国際がんセンター）咨询服务 ───
  'oici-initial-consultation': {
    slug: 'oici-initial-consultation',
    nameZhTw: '大阪國際癌症中心 - 前期諮詢服務',
    nameJa: '大阪国際がんセンター - 初期相談サービス',
    nameEn: 'OICI - Initial Consultation',
    descriptionZhTw: '病歷翻譯、大阪國際癌症中心諮詢、治療方案初步評估、費用概算',
    priceJpy: 221000,
    category: 'cancer_treatment',
    sortOrder: 133,
  },
  'oici-remote-consultation': {
    slug: 'oici-remote-consultation',
    nameZhTw: '大阪國際癌症中心 - 遠程會診服務',
    nameJa: '大阪国際がんセンター - 遠隔診療サービス',
    nameEn: 'OICI - Remote Consultation',
    descriptionZhTw: '與大阪國際癌症中心專科醫生遠程視頻會診、治療方案制定、費用概算',
    priceJpy: 243000,
    category: 'cancer_treatment',
    sortOrder: 134,
  },

  // ─── 近畿大学病院 咨询服务 ───
  'kindai-initial-consultation': {
    slug: 'kindai-initial-consultation',
    nameZhTw: '近畿大學醫院 - 前期諮詢服務',
    nameJa: '近畿大学病院 - 初期相談サービス',
    nameEn: 'Kindai University Hospital - Initial Consultation',
    descriptionZhTw: '病歷翻譯、近畿大學醫院諮詢、治療方案初步評估、費用概算',
    priceJpy: 221000,
    category: 'cancer_treatment',
    sortOrder: 135,
  },
  'kindai-remote-consultation': {
    slug: 'kindai-remote-consultation',
    nameZhTw: '近畿大學醫院 - 遠程會診服務',
    nameJa: '近畿大学病院 - 遠隔診療サービス',
    nameEn: 'Kindai University Hospital - Remote Consultation',
    descriptionZhTw: '與近畿大學醫院專科醫生遠程視頻會診、治療方案制定、費用概算',
    priceJpy: 243000,
    category: 'cancer_treatment',
    sortOrder: 136,
  },

  // ─── TIMC 健康体检套餐 ───
  'vip-member-course': {
    slug: 'vip-member-course',
    nameZhTw: 'VIP 會員套餐',
    nameJa: 'VIP会員コース',
    nameEn: 'VIP Member Course',
    descriptionZhTw: '全身PET-CT、腦MRI/MRA、上下消化道內視鏡、心臟超聲波、DWIBS、VIP專屬休息室',
    priceJpy: 1512500,
    category: 'health_checkup',
    sortOrder: 200,
  },
  'premium-cardiac-course': {
    slug: 'premium-cardiac-course',
    nameZhTw: '尊享心臟套餐',
    nameJa: 'プレミアム心臓コース',
    nameEn: 'Premium Cardiac Course',
    descriptionZhTw: 'PET-CT、心臟CT/MRI、心臟超聲波、胃鏡、血液檢查',
    priceJpy: 825000,
    category: 'health_checkup',
    sortOrder: 201,
  },
  'select-gastro-colonoscopy': {
    slug: 'select-gastro-colonoscopy',
    nameZhTw: '甄選胃腸套餐',
    nameJa: '胃腸セレクトコース',
    nameEn: 'Gastro + Colonoscopy Course',
    descriptionZhTw: 'PET-CT、上下消化道內視鏡、腹部超聲波、大腸CT、血液檢查',
    priceJpy: 825000,
    category: 'health_checkup',
    sortOrder: 202,
  },
  'select-gastroscopy': {
    slug: 'select-gastroscopy',
    nameZhTw: '甄選胃鏡套餐',
    nameJa: '胃カメラセレクト',
    nameEn: 'Gastroscopy Course',
    descriptionZhTw: 'PET-CT、胃鏡、腹部超聲波、幽門螺旋桿菌、血液檢查',
    priceJpy: 687500,
    category: 'health_checkup',
    sortOrder: 203,
  },
  'dwibs-cancer-screening': {
    slug: 'dwibs-cancer-screening',
    nameZhTw: 'DWIBS 癌症篩查',
    nameJa: 'DWIBSがんスクリーニング',
    nameEn: 'DWIBS Cancer Screening',
    descriptionZhTw: 'DWIBS全身MRI、腫瘤標記物、血液檢查、結果說明、無痛無輻射',
    priceJpy: 275000,
    category: 'health_checkup',
    sortOrder: 204,
  },
  'basic-checkup': {
    slug: 'basic-checkup',
    nameZhTw: '標準健診套餐',
    nameJa: 'スタンダード健診',
    nameEn: 'Standard Checkup Course',
    descriptionZhTw: 'PET-CT、腹部超聲波、血液檢查、尿液檢查、結果說明',
    priceJpy: 550000,
    category: 'health_checkup',
    sortOrder: 205,
  },

  // ─── SAI CLINIC 咨询服务 ───
  'sai-initial-consultation': {
    slug: 'sai-initial-consultation',
    nameZhTw: 'SAI CLINIC - 前期諮詢服務',
    nameJa: 'SAI CLINIC - 初期相談サービス',
    nameEn: 'SAI CLINIC - Initial Consultation',
    descriptionZhTw: '病歷翻譯、SAI CLINIC諮詢、醫美整形方案評估、費用概算',
    priceJpy: 221000,
    category: 'cosmetic_surgery',
    sortOrder: 299,
  },
  'sai-remote-consultation': {
    slug: 'sai-remote-consultation',
    nameZhTw: 'SAI CLINIC - 遠程諮詢服務',
    nameJa: 'SAI CLINIC - 遠隔相談サービス',
    nameEn: 'SAI CLINIC - Remote Consultation',
    descriptionZhTw: '與SAI CLINIC專科醫生遠程視頻諮詢、醫美整形方案制定、費用概算',
    priceJpy: 243000,
    category: 'cosmetic_surgery',
    sortOrder: 300,
  },

  // ─── SAI CLINIC 医美整形 ───
  'sai-lift-try': {
    slug: 'sai-lift-try',
    nameZhTw: 'SAI LIFT TRY 糸リフト體驗',
    nameJa: 'SAI LIFT TRY（糸リフト体験）',
    nameEn: 'SAI LIFT TRY - Thread Lift Trial',
    descriptionZhTw: '初次體驗推薦·自然提升效果·術後恢復快·含術後回診',
    priceJpy: 380000,
    category: 'cosmetic_surgery',
    sortOrder: 300,
  },
  'sai-lift-standard': {
    slug: 'sai-lift-standard',
    nameZhTw: 'SAI LIFT STANDARD 糸リフト標準',
    nameJa: 'SAI LIFT STANDARD（糸リフト標準）',
    nameEn: 'SAI LIFT STANDARD - Thread Lift Standard',
    descriptionZhTw: '最受歡迎·明顯提升效果·效果持續12-18個月·含術後回診',
    priceJpy: 680000,
    category: 'cosmetic_surgery',
    sortOrder: 301,
  },
  'sai-lift-perfect': {
    slug: 'sai-lift-perfect',
    nameZhTw: 'SAI LIFT PERFECT 糸リフト完美',
    nameJa: 'SAI LIFT PERFECT（糸リフト完美）',
    nameEn: 'SAI LIFT PERFECT - Thread Lift Premium',
    descriptionZhTw: '最高級方案·全臉全方位改善·最長持效期·VIP專屬服務',
    priceJpy: 980000,
    category: 'cosmetic_surgery',
    sortOrder: 302,
  },
  'sai-nasolabial-set': {
    slug: 'sai-nasolabial-set',
    nameZhTw: '法令紋改善套餐',
    nameJa: 'ほうれい線セット',
    nameEn: 'Nasolabial Fold Treatment Set',
    descriptionZhTw: '糸リフト+玻尿酸·針對法令紋的綜合解決方案',
    priceJpy: 378000,
    category: 'cosmetic_surgery',
    sortOrder: 310,
  },
  'sai-vline-set': {
    slug: 'sai-vline-set',
    nameZhTw: 'V臉線條套餐',
    nameJa: 'V-Lineセット',
    nameEn: 'V-Line Facial Contouring Set',
    descriptionZhTw: '精準脂肪溶解+線雕提升·打造理想V臉線條',
    priceJpy: 496000,
    category: 'cosmetic_surgery',
    sortOrder: 311,
  },
  'sai-neck-set': {
    slug: 'sai-neck-set',
    nameZhTw: '頸紋改善套餐',
    nameJa: '首シワセット',
    nameEn: 'Neck Wrinkle Treatment Set',
    descriptionZhTw: '糸リフト+玻尿酸·改善頸部細紋和鬆弛',
    priceJpy: 378000,
    category: 'cosmetic_surgery',
    sortOrder: 312,
  },
  'sai-eye-fatigue-set': {
    slug: 'sai-eye-fatigue-set',
    nameZhTw: '眼周疲勞改善套餐',
    nameJa: '目元セット',
    nameEn: 'Eye Fatigue Treatment Set',
    descriptionZhTw: '針對眼周暗沉·細紋的綜合年輕化方案',
    priceJpy: 378000,
    category: 'cosmetic_surgery',
    sortOrder: 313,
  },
  'sai-double-eyelid': {
    slug: 'sai-double-eyelid',
    nameZhTw: '自然雙眼皮（埋線法）',
    nameJa: '二重埋没法（ナチュラル）',
    nameEn: 'Natural Double Eyelid Surgery',
    descriptionZhTw: '微創埋線法·自然雙眼皮效果·1年保障',
    priceJpy: 300000,
    category: 'cosmetic_surgery',
    sortOrder: 320,
  },
  'sai-double-eyelid-premium': {
    slug: 'sai-double-eyelid-premium',
    nameZhTw: '精緻雙眼皮（6點連續法）',
    nameJa: '6点連続法二重',
    nameEn: 'Premium Double Eyelid - 6-Point Method',
    descriptionZhTw: '6點連續縫合法·精緻持久線條·5年保障',
    priceJpy: 580000,
    category: 'cosmetic_surgery',
    sortOrder: 321,
  },
  'sai-under-eye-reversehamra': {
    slug: 'sai-under-eye-reversehamra',
    nameZhTw: '黑眼圈·眼袋去除（Reverse Hamra）',
    nameJa: '裏ハムラ法',
    nameEn: 'Under-Eye Treatment - Reverse Hamra',
    descriptionZhTw: 'Reverse Hamra法·根本解決黑眼圈·脂肪重新分配',
    priceJpy: 880000,
    category: 'cosmetic_surgery',
    sortOrder: 322,
  },
  'sai-nose-thread': {
    slug: 'sai-nose-thread',
    nameZhTw: '線雕隆鼻（8線）',
    nameJa: 'SAI LIFT NOSE 8本',
    nameEn: 'Nose Thread Lift - 8 Threads',
    descriptionZhTw: '8根專用隆鼻線·無需開刀·自然挺拔鼻型',
    priceJpy: 560000,
    category: 'cosmetic_surgery',
    sortOrder: 330,
  },
  'sai-nose-implant': {
    slug: 'sai-nose-implant',
    nameZhTw: '硅膠隆鼻',
    nameJa: 'プロテーゼ隆鼻',
    nameEn: 'Silicone Nose Implant',
    descriptionZhTw: '硅膠假體隆鼻·永久效果·自然手感',
    priceJpy: 480000,
    category: 'cosmetic_surgery',
    sortOrder: 331,
  },
  'sai-botox-full-face': {
    slug: 'sai-botox-full-face',
    nameZhTw: 'Allergan全臉肉毒素（100單位）',
    nameJa: 'ボトックス全顔100単位',
    nameEn: 'Allergan Botox Full Face 100 Units',
    descriptionZhTw: 'Allergan正品100單位·全臉抗皺除紋·認證醫師施術',
    priceJpy: 240000,
    category: 'cosmetic_surgery',
    sortOrder: 340,
  },
  'sai-hyaluronic-1cc': {
    slug: 'sai-hyaluronic-1cc',
    nameZhTw: '玻尿酸注射（Juvéderm 1cc）',
    nameJa: 'ヒアルロン酸 1cc',
    nameEn: 'Hyaluronic Acid Filler 1cc',
    descriptionZhTw: 'Juvéderm系列高端玻尿酸·精準塑形填充',
    priceJpy: 148000,
    category: 'cosmetic_surgery',
    sortOrder: 341,
  },
  'sai-skin-rejuvenation': {
    slug: 'sai-skin-rejuvenation',
    nameZhTw: '肌膚再生·水光注射',
    nameJa: '水光注射+幹細胞エキス',
    nameEn: 'Skin Rejuvenation - Hydro + Stem Cell',
    descriptionZhTw: '水光注射+幹細胞精華·深層修復再生·改善膚質',
    priceJpy: 304000,
    category: 'cosmetic_surgery',
    sortOrder: 342,
  },
  'sai-exosome-therapy': {
    slug: 'sai-exosome-therapy',
    nameZhTw: '幹細胞外泌體療法（2-3次）',
    nameJa: 'エクソソーム療法',
    nameEn: 'Exosome Stem Cell Therapy',
    descriptionZhTw: '最前沿再生醫療·新鮮幹細胞外泌體·2-3次療程',
    priceJpy: 760000,
    category: 'cosmetic_surgery',
    sortOrder: 343,
  },
  'sai-fat-grafting-face': {
    slug: 'sai-fat-grafting-face',
    nameZhTw: '全臉脂肪填充',
    nameJa: '全顔脂肪注入',
    nameEn: 'Full Face Fat Grafting',
    descriptionZhTw: '自體脂肪提取+全臉無限注入·永久自然年輕化',
    priceJpy: 1760000,
    category: 'cosmetic_surgery',
    sortOrder: 350,
  },
  'sai-liposuction-face': {
    slug: 'sai-liposuction-face',
    nameZhTw: '面部吸脂（雙區）',
    nameJa: '脂肪吸引（2部位）',
    nameEn: 'Facial Liposuction - 2 Areas',
    descriptionZhTw: '精準面部吸脂（頰部+下顎）·永久減脂不反彈',
    priceJpy: 480000,
    category: 'cosmetic_surgery',
    sortOrder: 351,
  },
  'sai-nutrition-perfect': {
    slug: 'sai-nutrition-perfect',
    nameZhTw: '精密營養分析（82項）',
    nameJa: 'パーフェクト栄養解析',
    nameEn: 'Precision Nutrition Analysis - Perfect',
    descriptionZhTw: '82項血液檢測+專業營養分析+個人健康方案',
    priceJpy: 118000,
    category: 'cosmetic_surgery',
    sortOrder: 360,
  },
  'sai-vitamin-c-drip': {
    slug: 'sai-vitamin-c-drip',
    nameZhTw: '高濃度維C點滴（20g）',
    nameJa: '高濃度ビタミンC点滴20g',
    nameEn: 'High-Dose Vitamin C IV Drip 20g',
    descriptionZhTw: '超高濃度維生素C靜脈注射·美白抗氧化·免疫力提升',
    priceJpy: 26000,
    category: 'cosmetic_surgery',
    sortOrder: 361,
  },

  'sai-lift-collagen': {
    slug: 'sai-lift-collagen',
    nameZhTw: 'SAI LIFT COLLAGEN 膠原蛋白線雕',
    nameJa: 'SAI LIFT COLLAGEN（コラーゲン糸）',
    nameEn: 'SAI LIFT COLLAGEN - Collagen Thread Lift',
    descriptionZhTw: '韓國最新美容技術·束狀/網狀線強力促進膠原蛋白增生·緊緻回春',
    priceJpy: 280000,
    category: 'cosmetic_surgery',
    sortOrder: 303,
  },
  'sai-lift-single-thread': {
    slug: 'sai-lift-single-thread',
    nameZhTw: '線雕提升（單線）',
    nameJa: '糸リフト（1本）',
    nameEn: 'Thread Lift - Single Thread',
    descriptionZhTw: '依部位選擇最適合的線材·單線計價',
    priceJpy: 80000,
    category: 'cosmetic_surgery',
    sortOrder: 304,
  },
  'sai-lift-ldm': {
    slug: 'sai-lift-ldm',
    nameZhTw: 'LDM高密度超音波（減痛消腫）',
    nameJa: 'LDM（痛み・腫れ軽減）',
    nameEn: 'LDM - Pain & Swelling Reduction',
    descriptionZhTw: '高密度超音波軟化皮下脂肪·減少線雕術後疼痛腫脹瘀血',
    priceJpy: 42000,
    category: 'cosmetic_surgery',
    sortOrder: 305,
  },
  'sai-lift-jalupro': {
    slug: 'sai-lift-jalupro',
    nameZhTw: 'Jalupro超級保濕（線雕搭配）',
    nameJa: 'ジャルプロ・スーパーハイドロ（糸リフト併用）',
    nameEn: 'Jalupro Super Hydro - Thread Lift Combo',
    descriptionZhTw: '氨基酸+非交聯玻尿酸·促進膠原蛋白增生·延長線雕效果',
    priceJpy: 166000,
    category: 'cosmetic_surgery',
    sortOrder: 306,
  },
  'sai-fat-dissolve-cheeks': {
    slug: 'sai-fat-dissolve-cheeks',
    nameZhTw: '溶脂注射（頰部）',
    nameJa: '脂肪吸引注射（ホホ）',
    nameEn: 'Fat Dissolving Injection - Cheeks',
    descriptionZhTw: '精準溶脂·打造纖細臉部線條',
    priceJpy: 320000,
    category: 'cosmetic_surgery',
    sortOrder: 370,
  },
  'sai-fat-dissolve-chin': {
    slug: 'sai-fat-dissolve-chin',
    nameZhTw: '溶脂注射（下巴下方）',
    nameJa: '脂肪吸引注射（アゴ下）',
    nameEn: 'Fat Dissolving Injection - Under Chin',
    descriptionZhTw: '消除雙下巴·恢復下顎線條',
    priceJpy: 320000,
    category: 'cosmetic_surgery',
    sortOrder: 371,
  },
  'sai-fat-dissolve-cheeks-chin': {
    slug: 'sai-fat-dissolve-cheeks-chin',
    nameZhTw: '溶脂注射（頰部+下巴）',
    nameJa: '脂肪吸引注射（ホホ＋アゴ下）',
    nameEn: 'Fat Dissolving Injection - Cheeks + Chin',
    descriptionZhTw: '下臉部完美套組·頰部+下巴雙區域溶脂',
    priceJpy: 480000,
    category: 'cosmetic_surgery',
    sortOrder: 372,
  },
  'sai-fat-dissolve-arms': {
    slug: 'sai-fat-dissolve-arms',
    nameZhTw: '溶脂注射（手臂）',
    nameJa: '脂肪吸引注射（二の腕）',
    nameEn: 'Fat Dissolving Injection - Arms',
    descriptionZhTw: '告別蝴蝶袖·纖細手臂線條',
    priceJpy: 440000,
    category: 'cosmetic_surgery',
    sortOrder: 373,
  },
  'sai-lipo-cheeks': {
    slug: 'sai-lipo-cheeks',
    nameZhTw: '吸脂手術（頰部）',
    nameJa: '脂肪吸引（ホホ）',
    nameEn: 'Liposuction - Cheeks',
    descriptionZhTw: '手術吸脂·小臉輪廓更分明',
    priceJpy: 420000,
    category: 'cosmetic_surgery',
    sortOrder: 375,
  },
  'sai-lipo-chin': {
    slug: 'sai-lipo-chin',
    nameZhTw: '吸脂手術（下巴下方）',
    nameJa: '脂肪吸引（アゴ下）',
    nameEn: 'Liposuction - Under Chin',
    descriptionZhTw: '消除雙下巴·打造銳利下顎線',
    priceJpy: 420000,
    category: 'cosmetic_surgery',
    sortOrder: 376,
  },
  'sai-lipo-cheeks-chin': {
    slug: 'sai-lipo-cheeks-chin',
    nameZhTw: '吸脂手術（頰部+下巴）',
    nameJa: '脂肪吸引（ホホ＋アゴ下）',
    nameEn: 'Liposuction - Cheeks + Chin',
    descriptionZhTw: '下臉部完整吸脂·全方位小臉',
    priceJpy: 620000,
    category: 'cosmetic_surgery',
    sortOrder: 377,
  },
  'sai-lipo-arms': {
    slug: 'sai-lipo-arms',
    nameZhTw: '吸脂手術（手臂）',
    nameJa: '脂肪吸引（二の腕）',
    nameEn: 'Liposuction - Arms',
    descriptionZhTw: '纖細手臂·穿無袖更自信',
    priceJpy: 600000,
    category: 'cosmetic_surgery',
    sortOrder: 378,
  },
  'sai-fat-inject-harvest': {
    slug: 'sai-fat-inject-harvest',
    nameZhTw: '脂肪採取製備費',
    nameJa: '脂肪採取・作成料',
    nameEn: 'Fat Harvest & Preparation',
    descriptionZhTw: '從大腿採取脂肪+製備注入用脂肪',
    priceJpy: 380000,
    category: 'cosmetic_surgery',
    sortOrder: 380,
  },
  'sai-fat-inject-forehead': {
    slug: 'sai-fat-inject-forehead',
    nameZhTw: '自體脂肪填充（額頭）',
    nameJa: '脂肪注入（額）',
    nameEn: 'Fat Injection - Forehead',
    descriptionZhTw: '打造圓潤飽滿的額頭·韓式美學',
    priceJpy: 500000,
    category: 'cosmetic_surgery',
    sortOrder: 381,
  },
  'sai-fat-inject-temple': {
    slug: 'sai-fat-inject-temple',
    nameZhTw: '自體脂肪填充（太陽穴）',
    nameJa: '脂肪注入（こめかみ）',
    nameEn: 'Fat Injection - Temple',
    descriptionZhTw: '改善太陽穴凹陷·恢復蛋形臉輪廓',
    priceJpy: 320000,
    category: 'cosmetic_surgery',
    sortOrder: 382,
  },
  'sai-fat-inject-cheeks': {
    slug: 'sai-fat-inject-cheeks',
    nameZhTw: '自體脂肪填充（頰部）',
    nameJa: '脂肪注入（ホホ・頬骨下）',
    nameEn: 'Fat Injection - Cheeks',
    descriptionZhTw: '改善頰部凹陷·恢復蛋形臉輪廓',
    priceJpy: 320000,
    category: 'cosmetic_surgery',
    sortOrder: 383,
  },
  'sai-fat-inject-undereye': {
    slug: 'sai-fat-inject-undereye',
    nameZhTw: '自體脂肪填充（淚溝）',
    nameJa: '脂肪注入（目の下〜ゴルゴ線）',
    nameEn: 'Fat Injection - Under Eye / Tear Trough',
    descriptionZhTw: '改善淚溝·提升蘋果肌·消除黑眼圈',
    priceJpy: 300000,
    category: 'cosmetic_surgery',
    sortOrder: 384,
  },
  'sai-fat-inject-nasolabial': {
    slug: 'sai-fat-inject-nasolabial',
    nameZhTw: '自體脂肪填充（法令紋）',
    nameJa: '脂肪注入（ほうれい線）',
    nameEn: 'Fat Injection - Nasolabial Folds',
    descriptionZhTw: '填充法令紋·年輕化效果',
    priceJpy: 280000,
    category: 'cosmetic_surgery',
    sortOrder: 385,
  },
  'sai-fat-inject-marionette': {
    slug: 'sai-fat-inject-marionette',
    nameZhTw: '自體脂肪填充（木偶紋）',
    nameJa: '脂肪注入（口角・マリオネットライン）',
    nameEn: 'Fat Injection - Marionette Lines',
    descriptionZhTw: '改善嘴角紋路·回復年輕嘴角',
    priceJpy: 240000,
    category: 'cosmetic_surgery',
    sortOrder: 386,
  },
  'sai-fat-inject-chin': {
    slug: 'sai-fat-inject-chin',
    nameZhTw: '自體脂肪填充（下巴）',
    nameJa: '脂肪注入（アゴ）',
    nameEn: 'Fat Injection - Chin',
    descriptionZhTw: '塑造圓潤下巴·打造完美E線側顏',
    priceJpy: 220000,
    category: 'cosmetic_surgery',
    sortOrder: 387,
  },
  'sai-fat-inject-nanofat': {
    slug: 'sai-fat-inject-nanofat',
    nameZhTw: 'Nanofat奈米脂肪製備',
    nameJa: 'ナノファット作成',
    nameEn: 'Nanofat Preparation',
    descriptionZhTw: '將脂肪超微粒化·幹細胞修復膚質·改善細紋色澤',
    priceJpy: 320000,
    category: 'cosmetic_surgery',
    sortOrder: 388,
  },
  'sai-fat-inject-upper-eyelid': {
    slug: 'sai-fat-inject-upper-eyelid',
    nameZhTw: 'Nanofat填充（上眼瞼）',
    nameJa: '脂肪注入 上まぶた（ナノファット）',
    nameEn: 'Nanofat Injection - Upper Eyelid',
    descriptionZhTw: '改善上眼瞼細紋凹陷',
    priceJpy: 240000,
    category: 'cosmetic_surgery',
    sortOrder: 389,
  },
  'sai-fat-inject-lower-eyelid': {
    slug: 'sai-fat-inject-lower-eyelid',
    nameZhTw: 'Nanofat填充（下眼瞼）',
    nameJa: '脂肪注入 下まぶた（ナノファット）',
    nameEn: 'Nanofat Injection - Lower Eyelid',
    descriptionZhTw: '改善下眼瞼細紋·紅黑眼圈·凹陷',
    priceJpy: 240000,
    category: 'cosmetic_surgery',
    sortOrder: 390,
  },
  'sai-fat-inject-hands': {
    slug: 'sai-fat-inject-hands',
    nameZhTw: 'Nanofat填充（手背）',
    nameJa: '脂肪注入 手の甲（ナノファット）',
    nameEn: 'Nanofat Injection - Hands',
    descriptionZhTw: '改善手背血管突出·細紋·恢復年輕手部',
    priceJpy: 460000,
    category: 'cosmetic_surgery',
    sortOrder: 391,
  },
  'sai-double-eyelid-4point': {
    slug: 'sai-double-eyelid-4point',
    nameZhTw: '四點連續自然黏合法',
    nameJa: '4点連続自然癒着法',
    nameEn: '4-Point Continuous Adhesion Double Eyelid',
    descriptionZhTw: '自然雙眼皮·1根線4次往復·3年保障',
    priceJpy: 440000,
    category: 'cosmetic_surgery',
    sortOrder: 323,
  },
  'sai-eyelid-fat-removal': {
    slug: 'sai-eyelid-fat-removal',
    nameZhTw: '上眼瞼去脂',
    nameJa: '上瞼の脂肪除去',
    nameEn: 'Upper Eyelid Fat Removal',
    descriptionZhTw: '消除眼瞼浮腫·搭配埋線法效果更持久',
    priceJpy: 280000,
    category: 'cosmetic_surgery',
    sortOrder: 324,
  },
  'sai-full-incision-double-eyelid': {
    slug: 'sai-full-incision-double-eyelid',
    nameZhTw: '全切開雙眼皮手術',
    nameJa: '全切開二重術',
    nameEn: 'Full Incision Double Eyelid Surgery',
    descriptionZhTw: '適合眼皮厚·埋線多次脫落·鬆弛嚴重者',
    priceJpy: 640000,
    category: 'cosmetic_surgery',
    sortOrder: 325,
  },
  'sai-ptosis-nonsurgical': {
    slug: 'sai-ptosis-nonsurgical',
    nameZhTw: '非切開眼瞼下垂矯正',
    nameJa: '切らない眼瞼下垂術',
    nameEn: 'Non-Incisional Ptosis Correction',
    descriptionZhTw: '不切開·線縫法輕鬆提升眼力+雙眼皮',
    priceJpy: 420000,
    category: 'cosmetic_surgery',
    sortOrder: 326,
  },
  'sai-epicanthoplasty-z': {
    slug: 'sai-epicanthoplasty-z',
    nameZhTw: '開眼頭（Z形成術）',
    nameJa: '目頭切開（Z形成）',
    nameEn: 'Epicanthoplasty - Z Plasty',
    descriptionZhTw: '消除蒙古褶·MIX型/平行型雙眼皮·適合喜歡尖銳眼頭者',
    priceJpy: 440000,
    category: 'cosmetic_surgery',
    sortOrder: 327,
  },
  'sai-epicanthoplasty-korean': {
    slug: 'sai-epicanthoplasty-korean',
    nameZhTw: '韓式開眼頭',
    nameJa: '韓流目頭切開',
    nameEn: 'Korean Style Epicanthoplasty',
    descriptionZhTw: '消除蒙古褶·自然圓潤眼頭·疤痕不明顯',
    priceJpy: 500000,
    category: 'cosmetic_surgery',
    sortOrder: 328,
  },
  'sai-brow-lift': {
    slug: 'sai-brow-lift',
    nameZhTw: '眉下提拉（眉下切開）',
    nameJa: '眉下リフト（眉下切開）',
    nameEn: 'Sub-Brow Lift',
    descriptionZhTw: '眉下去除多餘皮膚·改善眼瞼下垂·恢復雙眼皮寬度',
    priceJpy: 700000,
    category: 'cosmetic_surgery',
    sortOrder: 329,
  },
  'sai-undereye-fat-removal': {
    slug: 'sai-undereye-fat-removal',
    nameZhTw: '下眼瞼去脂',
    nameJa: '下瞼の脂肪取り',
    nameEn: 'Lower Eyelid Fat Removal',
    descriptionZhTw: '從下眼瞼內側取脂·消除眼袋·無疤痕·適合20-30歲',
    priceJpy: 440000,
    category: 'cosmetic_surgery',
    sortOrder: 333,
  },
  'sai-undereye-hamra': {
    slug: 'sai-undereye-hamra',
    nameZhTw: '切開Hamra法',
    nameJa: '切開ハムラ法',
    nameEn: 'Open Hamra Technique',
    descriptionZhTw: '從下眼瞼外側手術·一次解決眼袋/凹凸/黑眼圈/淚溝/皮膚鬆弛·適合50歲以上',
    priceJpy: 1080000,
    category: 'cosmetic_surgery',
    sortOrder: 334,
  },
  'sai-undereye-skin-excision': {
    slug: 'sai-undereye-skin-excision',
    nameZhTw: '下眼瞼皮膚切除',
    nameJa: '下瞼の皮膚切除',
    nameEn: 'Lower Eyelid Skin Excision',
    descriptionZhTw: '切除下眼瞼多餘皮膚·改善細紋鬆弛',
    priceJpy: 660000,
    category: 'cosmetic_surgery',
    sortOrder: 335,
  },
  'sai-nose-thread-4': {
    slug: 'sai-nose-thread-4',
    nameZhTw: '線雕隆鼻（4線）',
    nameJa: 'SAI LIFT NOSE（4本）',
    nameEn: 'Nose Thread Lift - 4 Threads',
    descriptionZhTw: '4根鼻部專用線·不切開·自然挺拔',
    priceJpy: 320000,
    category: 'cosmetic_surgery',
    sortOrder: 332,
  },
  'sai-alar-reduction': {
    slug: 'sai-alar-reduction',
    nameZhTw: '縮鼻翼手術（內切法）',
    nameJa: '小鼻縮小術（内側法）',
    nameEn: 'Alar Reduction - Internal Method',
    descriptionZhTw: '改善鼻翼寬大·縮小鼻孔',
    priceJpy: 540000,
    category: 'cosmetic_surgery',
    sortOrder: 336,
  },
  'sai-philtrum-reduction': {
    slug: 'sai-philtrum-reduction',
    nameZhTw: '人中縮短術',
    nameJa: '人中短縮術',
    nameEn: 'Lip Lift / Philtrum Reduction',
    descriptionZhTw: '縮短人中·改善上唇薄·加齡人中也回春',
    priceJpy: 700000,
    category: 'cosmetic_surgery',
    sortOrder: 337,
  },
  'sai-botox-face-1area': {
    slug: 'sai-botox-face-1area',
    nameZhTw: 'Allergan肉毒素（臉部1部位）',
    nameJa: 'ボトックス 顔のしわ（1部位）',
    nameEn: 'Allergan Botox - Face 1 Area',
    descriptionZhTw: '額/眉間/鼻根/兔子紋/露齦笑/法令紋等·每部位最多20單位',
    priceJpy: 36000,
    category: 'cosmetic_surgery',
    sortOrder: 400,
  },
  'sai-botox-jaw': {
    slug: 'sai-botox-jaw',
    nameZhTw: 'Allergan肉毒素 咬肌（標準）',
    nameJa: 'ボトックス エラ（通常）',
    nameEn: 'Allergan Botox - Jaw Normal',
    descriptionZhTw: '瘦臉·改善磨牙/咬合',
    priceJpy: 88000,
    category: 'cosmetic_surgery',
    sortOrder: 401,
  },
  'sai-botox-jaw-double': {
    slug: 'sai-botox-jaw-double',
    nameZhTw: 'Allergan肉毒素 咬肌（加倍）',
    nameJa: 'ボトックス エラ（倍量）',
    nameEn: 'Allergan Botox - Jaw Double Dose',
    descriptionZhTw: '雙倍劑量瘦臉·更強效',
    priceJpy: 160000,
    category: 'cosmetic_surgery',
    sortOrder: 402,
  },
  'sai-botox-temporal': {
    slug: 'sai-botox-temporal',
    nameZhTw: 'Allergan肉毒素 顳肌',
    nameJa: 'ボトックス 側頭筋',
    nameEn: 'Allergan Botox - Temporal Muscle',
    descriptionZhTw: '瘦臉·改善磨牙/咬合/頭痛/眼部下垂',
    priceJpy: 88000,
    category: 'cosmetic_surgery',
    sortOrder: 403,
  },
  'sai-botox-neck-wrinkle': {
    slug: 'sai-botox-neck-wrinkle',
    nameZhTw: 'Allergan肉毒素 頸紋',
    nameJa: 'ボトックス 首のしわ',
    nameEn: 'Allergan Botox - Neck Wrinkles',
    descriptionZhTw: '改善頸部縱向皺紋',
    priceJpy: 96000,
    category: 'cosmetic_surgery',
    sortOrder: 404,
  },
  'sai-botox-lift': {
    slug: 'sai-botox-lift',
    nameZhTw: 'Allergan肉毒素提拉（闊頸肌）',
    nameJa: 'ボトックスリフト（広頚筋）',
    nameEn: 'Allergan Botox Lift - Platysma',
    descriptionZhTw: '臉部線條提拉效果',
    priceJpy: 96000,
    category: 'cosmetic_surgery',
    sortOrder: 405,
  },
  'sai-botox-skin': {
    slug: 'sai-botox-skin',
    nameZhTw: 'Allergan皮膚肉毒素',
    nameJa: 'スキンボトックス',
    nameEn: 'Allergan Skin Botox',
    descriptionZhTw: '淺層注射·縮毛孔·抑制皮脂汗液·預防痘痘',
    priceJpy: 96000,
    category: 'cosmetic_surgery',
    sortOrder: 406,
  },
  'sai-botox-face-50u': {
    slug: 'sai-botox-face-50u',
    nameZhTw: 'Allergan肉毒素 全臉（50單位）',
    nameJa: 'ボトックス 全顔お任せ（50単位）',
    nameEn: 'Allergan Botox - Full Face 50 Units',
    descriptionZhTw: '院長量身注射·最多50單位·自然表情同時改善',
    priceJpy: 140000,
    category: 'cosmetic_surgery',
    sortOrder: 407,
  },
  'sai-botox-armpit': {
    slug: 'sai-botox-armpit',
    nameZhTw: 'Allergan肉毒素 腋下止汗',
    nameJa: 'ボトックス ワキ（汗）',
    nameEn: 'Allergan Botox - Underarm Sweating',
    descriptionZhTw: '告別腋下汗漬困擾',
    priceJpy: 116000,
    category: 'cosmetic_surgery',
    sortOrder: 408,
  },
  'sai-botox-palms': {
    slug: 'sai-botox-palms',
    nameZhTw: 'Allergan肉毒素 手掌止汗',
    nameJa: 'ボトックス 手のひら（汗）',
    nameEn: 'Allergan Botox - Palm Sweating',
    descriptionZhTw: '手掌多汗症治療',
    priceJpy: 146000,
    category: 'cosmetic_surgery',
    sortOrder: 409,
  },
  'sai-botox-feet': {
    slug: 'sai-botox-feet',
    nameZhTw: 'Allergan肉毒素 腳底止汗',
    nameJa: 'ボトックス 足裏（汗）',
    nameEn: 'Allergan Botox - Foot Sweating',
    descriptionZhTw: '腳底多汗症治療',
    priceJpy: 146000,
    category: 'cosmetic_surgery',
    sortOrder: 410,
  },
  'sai-botox-shoulder': {
    slug: 'sai-botox-shoulder',
    nameZhTw: 'Allergan肉毒素 肩頸',
    nameJa: 'ボトックス 肩と首',
    nameEn: 'Allergan Botox - Shoulder & Neck',
    descriptionZhTw: '改善肩膀僵硬·頸部纖細',
    priceJpy: 114000,
    category: 'cosmetic_surgery',
    sortOrder: 411,
  },
  'sai-botox-calf': {
    slug: 'sai-botox-calf',
    nameZhTw: 'Allergan肉毒素 小腿',
    nameJa: 'ボトックス ふくらはぎ',
    nameEn: 'Allergan Botox - Calf Slimming',
    descriptionZhTw: '美腿·小腿纖細',
    priceJpy: 196000,
    category: 'cosmetic_surgery',
    sortOrder: 412,
  },
  'sai-botulax-face-1area': {
    slug: 'sai-botulax-face-1area',
    nameZhTw: 'Botulax肉毒素（臉部1部位）',
    nameJa: 'ボツラックス 顔のしわ（1部位）',
    nameEn: 'Botulax - Face 1 Area',
    descriptionZhTw: '韓國製·額/眉間/鼻根等·每部位最多20單位',
    priceJpy: 14000,
    category: 'cosmetic_surgery',
    sortOrder: 415,
  },
  'sai-botulax-jaw': {
    slug: 'sai-botulax-jaw',
    nameZhTw: 'Botulax肉毒素 咬肌（標準）',
    nameJa: 'ボツラックス エラ（通常）',
    nameEn: 'Botulax - Jaw Normal',
    descriptionZhTw: '韓國製·瘦臉·改善磨牙/咬合',
    priceJpy: 36000,
    category: 'cosmetic_surgery',
    sortOrder: 416,
  },
  'sai-botulax-jaw-double': {
    slug: 'sai-botulax-jaw-double',
    nameZhTw: 'Botulax肉毒素 咬肌（加倍）',
    nameJa: 'ボツラックス エラ（倍量）',
    nameEn: 'Botulax - Jaw Double Dose',
    descriptionZhTw: '韓國製·雙倍劑量瘦臉',
    priceJpy: 64000,
    category: 'cosmetic_surgery',
    sortOrder: 417,
  },
  'sai-botulax-temporal': {
    slug: 'sai-botulax-temporal',
    nameZhTw: 'Botulax肉毒素 顳肌',
    nameJa: 'ボツラックス 側頭筋',
    nameEn: 'Botulax - Temporal Muscle',
    descriptionZhTw: '韓國製·瘦臉/改善頭痛',
    priceJpy: 46000,
    category: 'cosmetic_surgery',
    sortOrder: 418,
  },
  'sai-botulax-neck-wrinkle': {
    slug: 'sai-botulax-neck-wrinkle',
    nameZhTw: 'Botulax肉毒素 頸紋',
    nameJa: 'ボツラックス 首のしわ',
    nameEn: 'Botulax - Neck Wrinkles',
    descriptionZhTw: '韓國製·改善頸部縱向皺紋',
    priceJpy: 50000,
    category: 'cosmetic_surgery',
    sortOrder: 419,
  },
  'sai-botulax-lift': {
    slug: 'sai-botulax-lift',
    nameZhTw: 'Botulax肉毒素提拉',
    nameJa: 'ボツラックス ボトックスリフト',
    nameEn: 'Botulax Lift - Platysma',
    descriptionZhTw: '韓國製·臉部線條提拉',
    priceJpy: 50000,
    category: 'cosmetic_surgery',
    sortOrder: 420,
  },
  'sai-botulax-skin': {
    slug: 'sai-botulax-skin',
    nameZhTw: 'Botulax皮膚肉毒素',
    nameJa: 'ボツラックス スキンボトックス',
    nameEn: 'Botulax - Skin Botox',
    descriptionZhTw: '韓國製·縮毛孔·抑制皮脂·預防痘痘',
    priceJpy: 66000,
    category: 'cosmetic_surgery',
    sortOrder: 421,
  },
  'sai-botulax-face-50u': {
    slug: 'sai-botulax-face-50u',
    nameZhTw: 'Botulax肉毒素 全臉（50單位）',
    nameJa: 'ボツラックス 全顔お任せ（50単位）',
    nameEn: 'Botulax - Full Face 50 Units',
    descriptionZhTw: '韓國製·院長量身注射·最多50單位',
    priceJpy: 64000,
    category: 'cosmetic_surgery',
    sortOrder: 422,
  },
  'sai-botulax-face-100u': {
    slug: 'sai-botulax-face-100u',
    nameZhTw: 'Botulax肉毒素 全臉（100單位）',
    nameJa: 'ボツラックス 全顔お任せ（100単位）',
    nameEn: 'Botulax - Full Face 100 Units',
    descriptionZhTw: '韓國製·院長精心設計·最多100單位·全面抗皺',
    priceJpy: 116000,
    category: 'cosmetic_surgery',
    sortOrder: 423,
  },
  'sai-botulax-armpit': {
    slug: 'sai-botulax-armpit',
    nameZhTw: 'Botulax肉毒素 腋下止汗',
    nameJa: 'ボツラックス ワキ（汗）',
    nameEn: 'Botulax - Underarm Sweating',
    descriptionZhTw: '韓國製·腋下止汗',
    priceJpy: 42000,
    category: 'cosmetic_surgery',
    sortOrder: 424,
  },
  'sai-botulax-palms': {
    slug: 'sai-botulax-palms',
    nameZhTw: 'Botulax肉毒素 手掌止汗',
    nameJa: 'ボツラックス 手のひら（汗）',
    nameEn: 'Botulax - Palm Sweating',
    descriptionZhTw: '韓國製·手掌多汗症治療',
    priceJpy: 66000,
    category: 'cosmetic_surgery',
    sortOrder: 425,
  },
  'sai-botulax-feet': {
    slug: 'sai-botulax-feet',
    nameZhTw: 'Botulax肉毒素 腳底止汗',
    nameJa: 'ボツラックス 足裏（汗）',
    nameEn: 'Botulax - Foot Sweating',
    descriptionZhTw: '韓國製·腳底多汗症治療',
    priceJpy: 66000,
    category: 'cosmetic_surgery',
    sortOrder: 426,
  },
  'sai-botulax-shoulder': {
    slug: 'sai-botulax-shoulder',
    nameZhTw: 'Botulax肉毒素 肩頸',
    nameJa: 'ボツラックス 肩と首',
    nameEn: 'Botulax - Shoulder & Neck',
    descriptionZhTw: '韓國製·肩膀僵硬改善·頸部纖細',
    priceJpy: 56000,
    category: 'cosmetic_surgery',
    sortOrder: 427,
  },
  'sai-botulax-calf': {
    slug: 'sai-botulax-calf',
    nameZhTw: 'Botulax肉毒素 小腿',
    nameJa: 'ボツラックス ふくらはぎ',
    nameEn: 'Botulax - Calf Slimming',
    descriptionZhTw: '韓國製·美腿·小腿纖細',
    priceJpy: 96000,
    category: 'cosmetic_surgery',
    sortOrder: 428,
  },
  'sai-ha-volbella': {
    slug: 'sai-ha-volbella',
    nameZhTw: '玻尿酸 Volbella（Juvéderm）',
    nameJa: 'ヒアルロン酸 ボルベラ（ジュビダーム）',
    nameEn: 'Hyaluronic Acid - Volbella',
    descriptionZhTw: '柔軟質地·適用於淚溝/嘴唇',
    priceJpy: 148000,
    category: 'cosmetic_surgery',
    sortOrder: 430,
  },
  'sai-ha-volift': {
    slug: 'sai-ha-volift',
    nameZhTw: '玻尿酸 Volift（Juvéderm）',
    nameJa: 'ヒアルロン酸 ボリフト（ジュビダーム）',
    nameEn: 'Hyaluronic Acid - Volift',
    descriptionZhTw: '中等硬度·適用於額/太陽穴/頰/法令紋',
    priceJpy: 148000,
    category: 'cosmetic_surgery',
    sortOrder: 431,
  },
  'sai-ha-voluma': {
    slug: 'sai-ha-voluma',
    nameZhTw: '玻尿酸 Voluma（Juvéderm）',
    nameJa: 'ヒアルロン酸 ボリューマ（ジュビダーム）',
    nameEn: 'Hyaluronic Acid - Voluma',
    descriptionZhTw: '較硬質地·適用於額/淚溝/蘋果肌/法令紋',
    priceJpy: 148000,
    category: 'cosmetic_surgery',
    sortOrder: 432,
  },
  'sai-ha-volux': {
    slug: 'sai-ha-volux',
    nameZhTw: '玻尿酸 Volux（Juvéderm）',
    nameJa: 'ヒアルロン酸 ボラックス（ジュビダーム）',
    nameEn: 'Hyaluronic Acid - Volux',
    descriptionZhTw: '最硬質地·適用於鼻根/下巴',
    priceJpy: 156000,
    category: 'cosmetic_surgery',
    sortOrder: 433,
  },
  'sai-ha-dissolve': {
    slug: 'sai-ha-dissolve',
    nameZhTw: '玻尿酸溶解術',
    nameJa: 'ヒアルロニダーゼ（ヒアルロン酸溶解）',
    nameEn: 'Hyaluronidase - HA Dissolving',
    descriptionZhTw: '溶解玻尿酸的治療',
    priceJpy: 60000,
    category: 'cosmetic_surgery',
    sortOrder: 434,
  },
  'sai-ldm-face': {
    slug: 'sai-ldm-face',
    nameZhTw: 'LDM高密度超音波（臉部）',
    nameJa: 'LDM（顔）',
    nameEn: 'LDM Ultrasound - Face',
    descriptionZhTw: '保濕·彈力·緊緻·膠原蛋白增生·提亮·改善痘痘紅腫',
    priceJpy: 42000,
    category: 'cosmetic_surgery',
    sortOrder: 440,
  },
  'sai-ldm-face-neck': {
    slug: 'sai-ldm-face-neck',
    nameZhTw: 'LDM高密度超音波（臉+頸）',
    nameJa: 'LDM（顔＋首）',
    nameEn: 'LDM Ultrasound - Face + Neck',
    descriptionZhTw: '臉部+頸部全方位超音波護理',
    priceJpy: 56000,
    category: 'cosmetic_surgery',
    sortOrder: 441,
  },
  'sai-ldm-stemcell-face': {
    slug: 'sai-ldm-stemcell-face',
    nameZhTw: 'LDM+幹細胞上清液（臉部）',
    nameJa: 'LDM＋幹細胞上清液（顔）',
    nameEn: 'LDM + Stem Cell Supernatant - Face',
    descriptionZhTw: '搭配幹細胞培養上清液·促進細胞再生·改善膚質',
    priceJpy: 52000,
    category: 'cosmetic_surgery',
    sortOrder: 442,
  },
  'sai-ldm-stemcell-face-neck': {
    slug: 'sai-ldm-stemcell-face-neck',
    nameZhTw: 'LDM+幹細胞上清液（臉+頸）',
    nameJa: 'LDM＋幹細胞上清液（顔＋首）',
    nameEn: 'LDM + Stem Cell Supernatant - Face + Neck',
    descriptionZhTw: '臉部+頸部·幹細胞再生護理',
    priceJpy: 66000,
    category: 'cosmetic_surgery',
    sortOrder: 443,
  },
  'sai-nurture-collage': {
    slug: 'sai-nurture-collage',
    nameZhTw: '肌膚養護注射 Collage膠原蛋白',
    nameJa: '肌育注射 コラージュ',
    nameEn: 'Skin Nurture - Collage Collagen',
    descriptionZhTw: '高效安全的膠原蛋白製劑·改善眼下凹陷/頬凹/細紋/青黑眼圈',
    priceJpy: 156000,
    category: 'cosmetic_surgery',
    sortOrder: 450,
  },
  'sai-nurture-jalupro': {
    slug: 'sai-nurture-jalupro',
    nameZhTw: '肌膚養護注射 Jalupro超級保濕',
    nameJa: '肌育注射 ジャルプロ・スーパーハイドロ',
    nameEn: 'Skin Nurture - Jalupro Super Hydro',
    descriptionZhTw: '氨基酸+非交聯玻尿酸·定期營養補給·緊緻彈力',
    priceJpy: 166000,
    category: 'cosmetic_surgery',
    sortOrder: 451,
  },
  'sai-nurture-sunekos': {
    slug: 'sai-nurture-sunekos',
    nameZhTw: '肌膚養護注射 Sunekos Performa',
    nameJa: '肌育注射 スネコス・パフォルマ',
    nameEn: 'Skin Nurture - Sunekos Performa',
    descriptionZhTw: '非交聯玻尿酸+6種氨基酸·促進膠原蛋白和彈性蛋白·改善膚質',
    priceJpy: 66000,
    category: 'cosmetic_surgery',
    sortOrder: 452,
  },
  'sai-nurture-hydro': {
    slug: 'sai-nurture-hydro',
    nameZhTw: '肌膚養護注射 Hydro水光肌',
    nameJa: '肌育注射 ハイドロ水光肌',
    nameEn: 'Skin Nurture - Hydro Glow Skin',
    descriptionZhTw: '3種分子量玻尿酸·細胞再生+極致保水·彈力光澤',
    priceJpy: 148000,
    category: 'cosmetic_surgery',
    sortOrder: 453,
  },
  'sai-nurture-hydro-botox': {
    slug: 'sai-nurture-hydro-botox',
    nameZhTw: '肌膚養護注射 Hydro+肉毒素',
    nameJa: '肌育注射 ハイドロ＋ボトックス',
    nameEn: 'Skin Nurture - Hydro + Botox',
    descriptionZhTw: '保水+縮毛孔·抑制皮脂·膚質更細緻',
    priceJpy: 226000,
    category: 'cosmetic_surgery',
    sortOrder: 454,
  },
  'sai-nurture-hydro-botox-stemcell': {
    slug: 'sai-nurture-hydro-botox-stemcell',
    nameZhTw: '肌膚養護注射 完美美肌雞尾酒',
    nameJa: '肌育注射 ハイドロ＋ボトックス＋臍帯幹細胞',
    nameEn: 'Skin Nurture - Perfect Beauty Cocktail',
    descriptionZhTw: '保水+縮毛孔+再生·全效合一·從肌底恢復彈力光澤年輕',
    priceJpy: 378000,
    category: 'cosmetic_surgery',
    sortOrder: 456,
  },
  'sai-nurture-pluryal-densify': {
    slug: 'sai-nurture-pluryal-densify',
    nameZhTw: '肌膚養護注射 Pluryal Densify',
    nameJa: '肌育注射 プルリアル・デンシファイ',
    nameEn: 'Skin Nurture - Pluryal Densify',
    descriptionZhTw: '多核苷酸自我修復·改善膠原蛋白/彈力/透明感/皺紋/毛孔·全臉',
    priceJpy: 158000,
    category: 'cosmetic_surgery',
    sortOrder: 457,
  },
  'sai-nurture-pluryal-silk': {
    slug: 'sai-nurture-pluryal-silk',
    nameZhTw: '肌膚養護注射 Pluryal Silk',
    nameJa: '肌育注射 プルリアル・シルク',
    nameEn: 'Skin Nurture - Pluryal Silk',
    descriptionZhTw: '多核苷酸自我修復·適用眼周·改善彈力透明感',
    priceJpy: 132000,
    category: 'cosmetic_surgery',
    sortOrder: 458,
  },
  'sai-nurture-pluryal-bio': {
    slug: 'sai-nurture-pluryal-bio',
    nameZhTw: '肌膚養護注射 Pluryal Bio Sculpture',
    nameJa: '肌育注射 プルリアル バイオスカルプチャー',
    nameEn: 'Skin Nurture - Pluryal Bio Sculpture',
    descriptionZhTw: '交聯玻尿酸·活化纖維芽細胞·促進膠原蛋白和彈性蛋白生成',
    priceJpy: 148000,
    category: 'cosmetic_surgery',
    sortOrder: 459,
  },
  'sai-nurture-olidia': {
    slug: 'sai-nurture-olidia',
    nameZhTw: '肌膚養護注射 Olidia',
    nameJa: '肌育注射 オリディア',
    nameEn: 'Skin Nurture - Olidia',
    descriptionZhTw: '聚左旋乳酸(PLLA)·促進膠原蛋白生成·彈力/體積/皺紋改善·痘疤也有效',
    priceJpy: 140000,
    category: 'cosmetic_surgery',
    sortOrder: 460,
  },
  'sai-nurture-botox': {
    slug: 'sai-nurture-botox',
    nameZhTw: '肌膚養護注射 微量肉毒素',
    nameJa: '肌育注射 ボトックス',
    nameEn: 'Skin Nurture - Micro Botox',
    descriptionZhTw: '微量肉毒素(Micro Botox)·縮毛孔·抑制皮脂汗液·改善膚質',
    priceJpy: 98000,
    category: 'cosmetic_surgery',
    sortOrder: 461,
  },
  'sai-nurture-stemcell-fd': {
    slug: 'sai-nurture-stemcell-fd',
    nameZhTw: '肌膚養護注射 臍帶幹細胞上清液（凍乾）',
    nameJa: '肌育注射 臍帯幹細胞上清液（フリーズドライ）',
    nameEn: 'Skin Nurture - Umbilical Stem Cell (Freeze-Dried)',
    descriptionZhTw: '臍帶幹細胞萃取·高再生能力·改善彈力光澤細紋',
    priceJpy: 186000,
    category: 'cosmetic_surgery',
    sortOrder: 462,
  },
  'sai-nurture-pdf-fd': {
    slug: 'sai-nurture-pdf-fd',
    nameZhTw: '肌膚養護注射 PDF-FD療法（外泌體）',
    nameJa: '肌育注射 PDF-FD療法（エクソソーム）',
    nameEn: 'Skin Nurture - PDF-FD Exosome Therapy',
    descriptionZhTw: '自體血液萃取生長因子·外泌體直接注入·安全高效回春',
    priceJpy: 456000,
    category: 'cosmetic_surgery',
    sortOrder: 463,
  },
  'sai-nurture-skinvive': {
    slug: 'sai-nurture-skinvive',
    nameZhTw: '肌膚養護注射 SkinVive（Juvéderm）',
    nameJa: '肌育注射 スキンバイブ（ジュビダーム）',
    nameEn: 'Skin Nurture - SkinVive by Juvéderm',
    descriptionZhTw: '保水性(潤澤)+彈力性(緊緻)+細紋改善·頸部深層皺紋/毛孔改善',
    priceJpy: 130000,
    category: 'cosmetic_surgery',
    sortOrder: 464,
  },
  'sai-meso-hydro': {
    slug: 'sai-meso-hydro',
    nameZhTw: '水光注射 Hydro水光肌',
    nameJa: '水光注射 ハイドロ水光肌',
    nameEn: 'Mesotherapy - Hydro Glow Skin',
    descriptionZhTw: '3種分子量玻尿酸·細胞再生+保水·彈力光澤提升',
    priceJpy: 118000,
    category: 'cosmetic_surgery',
    sortOrder: 470,
  },
  'sai-meso-pluryal-densify': {
    slug: 'sai-meso-pluryal-densify',
    nameZhTw: '水光注射 Pluryal Densify',
    nameJa: '水光注射 プルリアル・デンシファイ',
    nameEn: 'Mesotherapy - Pluryal Densify',
    descriptionZhTw: '多核苷酸自我修復力·改善膠原蛋白/彈力/透明感·全臉',
    priceJpy: 128000,
    category: 'cosmetic_surgery',
    sortOrder: 471,
  },
  'sai-meso-pluryal-silk': {
    slug: 'sai-meso-pluryal-silk',
    nameZhTw: '水光注射 Pluryal Silk',
    nameJa: '水光注射 プルリアル・シルク',
    nameEn: 'Mesotherapy - Pluryal Silk',
    descriptionZhTw: '多核苷酸自我修復力·適用眼周',
    priceJpy: 102000,
    category: 'cosmetic_surgery',
    sortOrder: 472,
  },
  'sai-meso-eye-deal': {
    slug: 'sai-meso-eye-deal',
    nameZhTw: '水光注射 Rejuview EYE DEAL',
    nameJa: '水光注射 リジュビュー・EYE DEAL',
    nameEn: 'Mesotherapy - Rejuview EYE DEAL',
    descriptionZhTw: '眼部專用高濃度多核苷酸·改善眼下細紋/暗沉/黑眼圈',
    priceJpy: 96000,
    category: 'cosmetic_surgery',
    sortOrder: 473,
  },
  'sai-meso-aqua-bomb': {
    slug: 'sai-meso-aqua-bomb',
    nameZhTw: '水光注射 Rejuview AQUA BOMB',
    nameJa: '水光注射 リジュビュー・AQUA BOMB',
    nameEn: 'Mesotherapy - Rejuview AQUA BOMB',
    descriptionZhTw: '高保濕皮膚助推劑·改善乾燥細紋·穀胱甘肽美白提亮',
    priceJpy: 76000,
    category: 'cosmetic_surgery',
    sortOrder: 474,
  },
  'sai-meso-jalupro': {
    slug: 'sai-meso-jalupro',
    nameZhTw: '水光注射 Jalupro超級保濕',
    nameJa: '水光注射 ジャルプロ・スーパーハイドロ',
    nameEn: 'Mesotherapy - Jalupro Super Hydro',
    descriptionZhTw: '氨基酸+非交聯玻尿酸·定期營養補給·緊緻彈力',
    priceJpy: 146000,
    category: 'cosmetic_surgery',
    sortOrder: 475,
  },
  'sai-meso-stemcell-fd': {
    slug: 'sai-meso-stemcell-fd',
    nameZhTw: '水光注射 臍帶幹細胞上清液（凍乾）',
    nameJa: '水光注射 臍帯幹細胞上清液（フリーズドライ）',
    nameEn: 'Mesotherapy - Umbilical Stem Cell (Freeze-Dried)',
    descriptionZhTw: '高再生能力·改善彈力光澤細紋·疲勞回復·性機能改善',
    priceJpy: 166000,
    category: 'cosmetic_surgery',
    sortOrder: 476,
  },
  'sai-meso-stemcell-frozen': {
    slug: 'sai-meso-stemcell-frozen',
    nameZhTw: '水光注射 臍帶幹細胞上清液（新鮮凍結）',
    nameJa: '水光注射 臍帯幹細胞上清液（新鮮凍結品）',
    nameEn: 'Mesotherapy - Umbilical Stem Cell (Fresh Frozen)',
    descriptionZhTw: '新鮮凍結品10cc·2-3次份量·最高品質再生療法',
    priceJpy: 700000,
    category: 'cosmetic_surgery',
    sortOrder: 477,
  },
  'sai-meso-botox-add': {
    slug: 'sai-meso-botox-add',
    nameZhTw: '水光注射 追加肉毒素',
    nameJa: '水光注射 ボトックス追加',
    nameEn: 'Mesotherapy - Botox Add-on',
    descriptionZhTw: '追加肉毒素·縮毛孔·抑制皮脂汗液·改善膚質',
    priceJpy: 60000,
    category: 'cosmetic_surgery',
    sortOrder: 478,
  },
  'sai-fat-x-core': {
    slug: 'sai-fat-x-core',
    nameZhTw: '溶脂注射 Fat X Core（1cc）',
    nameJa: '脂肪溶解注射 Fat X Core（1cc）',
    nameEn: 'Fat Dissolving - Fat X Core 1cc',
    descriptionZhTw: '日本最高濃度脫氧膽酸·不反彈·高效溶脂+防止皮膚鬆弛',
    priceJpy: 16000,
    category: 'cosmetic_surgery',
    sortOrder: 480,
  },
  'sai-subcision-4': {
    slug: 'sai-subcision-4',
    nameZhTw: '皮下剝離術（2×2cm）',
    nameJa: 'サブシジョン（2×2cm）',
    nameEn: 'Subcision - 2×2cm',
    descriptionZhTw: '剝離皮下粘連·改善痘疤/水痘凹洞',
    priceJpy: 44000,
    category: 'cosmetic_surgery',
    sortOrder: 481,
  },
  'sai-subcision-16': {
    slug: 'sai-subcision-16',
    nameZhTw: '皮下剝離術（4×4cm）',
    nameJa: 'サブシジョン（4×4cm）',
    nameEn: 'Subcision - 4×4cm',
    descriptionZhTw: '剝離皮下粘連·改善痘疤/水痘凹洞',
    priceJpy: 156000,
    category: 'cosmetic_surgery',
    sortOrder: 482,
  },
  'sai-subcision-36': {
    slug: 'sai-subcision-36',
    nameZhTw: '皮下剝離術（6×6cm）',
    nameJa: 'サブシジョン（6×6cm）',
    nameEn: 'Subcision - 6×6cm',
    descriptionZhTw: '剝離皮下粘連·改善痘疤/水痘凹洞',
    priceJpy: 336000,
    category: 'cosmetic_surgery',
    sortOrder: 483,
  },
  'sai-subcision-full': {
    slug: 'sai-subcision-full',
    nameZhTw: '皮下剝離術（全臉）',
    nameJa: 'サブシジョン（全顔）',
    nameEn: 'Subcision - Full Face',
    descriptionZhTw: '全臉皮下粘連剝離·全面改善凹洞痘疤',
    priceJpy: 540000,
    category: 'cosmetic_surgery',
    sortOrder: 484,
  },
  'sai-shopping-lift-20': {
    slug: 'sai-shopping-lift-20',
    nameZhTw: '購物提拉（20根）',
    nameJa: 'ショッピングリフト（20本）',
    nameEn: 'Shopping Lift - 20 Threads',
    descriptionZhTw: '溶解線植入·促進膠原蛋白·緊緻提升·最小停工期',
    priceJpy: 84000,
    category: 'cosmetic_surgery',
    sortOrder: 485,
  },
  'sai-shopping-lift-40': {
    slug: 'sai-shopping-lift-40',
    nameZhTw: '購物提拉（40根）',
    nameJa: 'ショッピングリフト（40本）',
    nameEn: 'Shopping Lift - 40 Threads',
    descriptionZhTw: '溶解線植入·促進膠原蛋白·緊緻提升',
    priceJpy: 156000,
    category: 'cosmetic_surgery',
    sortOrder: 486,
  },
  'sai-shopping-lift-60': {
    slug: 'sai-shopping-lift-60',
    nameZhTw: '購物提拉（60根）',
    nameJa: 'ショッピングリフト（60本）',
    nameEn: 'Shopping Lift - 60 Threads',
    descriptionZhTw: '溶解線植入·促進膠原蛋白·緊緻提升',
    priceJpy: 236000,
    category: 'cosmetic_surgery',
    sortOrder: 487,
  },
  'sai-shopping-lift-80': {
    slug: 'sai-shopping-lift-80',
    nameZhTw: '購物提拉（80根）',
    nameJa: 'ショッピングリフト（80本）',
    nameEn: 'Shopping Lift - 80 Threads',
    descriptionZhTw: '溶解線植入·促進膠原蛋白·緊緻提升',
    priceJpy: 316000,
    category: 'cosmetic_surgery',
    sortOrder: 488,
  },
  'sai-shopping-lift-100': {
    slug: 'sai-shopping-lift-100',
    nameZhTw: '購物提拉（100根）',
    nameJa: 'ショッピングリフト（100本）',
    nameEn: 'Shopping Lift - 100 Threads',
    descriptionZhTw: '溶解線植入·促進膠原蛋白·緊緻提升·最大效果',
    priceJpy: 396000,
    category: 'cosmetic_surgery',
    sortOrder: 489,
  },
  'sai-peel-reverse': {
    slug: 'sai-peel-reverse',
    nameZhTw: '逆轉煥膚',
    nameJa: 'リバースピール',
    nameEn: 'Reverse Peel',
    descriptionZhTw: '針對肝斑&色素沉著·3層藥劑從表皮到真皮深層改善',
    priceJpy: 36000,
    category: 'cosmetic_surgery',
    sortOrder: 490,
  },
  'sai-peel-milano': {
    slug: 'sai-peel-milano',
    nameZhTw: '米蘭煥膚',
    nameJa: 'ミラノ・リピール',
    nameEn: 'Milano Repeel',
    descriptionZhTw: '5種酸促進肌膚代謝更新·透明感·改善痘痘/毛孔',
    priceJpy: 30000,
    category: 'cosmetic_surgery',
    sortOrder: 491,
  },
  'sai-peel-massage': {
    slug: 'sai-peel-massage',
    nameZhTw: '按摩煥膚（膠原蛋白煥膚）',
    nameJa: 'マッサージピール（コラーゲンピール）',
    nameEn: 'Massage Peel - Collagen Peel',
    descriptionZhTw: '邊按摩邊將藥劑滲透至真皮層·促進膠原蛋白生成·改善彈力/細紋/鬆弛',
    priceJpy: 30000,
    category: 'cosmetic_surgery',
    sortOrder: 492,
  },
  'sai-aga-cocktail-partial': {
    slug: 'sai-aga-cocktail-partial',
    nameZhTw: 'SAI CLINIC生髮雞尾酒（前額+分線+頭頂）',
    nameJa: 'SAI CLINIC発毛カクテル（生え際＋分け目＋頭頂部）',
    nameEn: 'SAI CLINIC Hair Growth Cocktail - Partial',
    descriptionZhTw: '生長因子+Minoxidil+12種原創生髮成分·水光注射深層滲透',
    priceJpy: 116000,
    category: 'cosmetic_surgery',
    sortOrder: 500,
  },
  'sai-aga-cocktail-full': {
    slug: 'sai-aga-cocktail-full',
    nameZhTw: 'SAI CLINIC生髮雞尾酒（全頭）',
    nameJa: 'SAI CLINIC発毛カクテル（頭全体）',
    nameEn: 'SAI CLINIC Hair Growth Cocktail - Full Head',
    descriptionZhTw: '全頭水光注射·深層滲透毛母細胞周圍·全面促進生髮',
    priceJpy: 220000,
    category: 'cosmetic_surgery',
    sortOrder: 501,
  },
  'sai-aga-stemcell-fd': {
    slug: 'sai-aga-stemcell-fd',
    nameZhTw: '生髮治療 臍帶幹細胞上清液（凍乾）',
    nameJa: '薄毛治療 臍帯幹細胞上清液（フリーズドライ）',
    nameEn: 'Hair Loss - Umbilical Stem Cell (Freeze-Dried)',
    descriptionZhTw: '幹細胞萃取生長因子·活化毛根·促進生髮·改善髮質·白髮變黑',
    priceJpy: 178000,
    category: 'cosmetic_surgery',
    sortOrder: 502,
  },
  'sai-aga-stemcell-frozen': {
    slug: 'sai-aga-stemcell-frozen',
    nameZhTw: '生髮治療 臍帶幹細胞上清液（新鮮凍結）',
    nameJa: '薄毛治療 臍帯幹細胞上清液（新鮮凍結品）',
    nameEn: 'Hair Loss - Umbilical Stem Cell (Fresh Frozen)',
    descriptionZhTw: '新鮮凍結品·2次份量·最高品質·活化毛根促進生髮',
    priceJpy: 700000,
    category: 'cosmetic_surgery',
    sortOrder: 503,
  },
  'sai-aga-pdf-fd': {
    slug: 'sai-aga-pdf-fd',
    nameZhTw: '生髮治療 PDF-FD療法',
    nameJa: '薄毛治療 PDF-FD療法',
    nameEn: 'Hair Loss - PDF-FD Therapy',
    descriptionZhTw: '自體血液萃取生長因子·直接注入頭皮·活化毛根',
    priceJpy: 456000,
    category: 'cosmetic_surgery',
    sortOrder: 504,
  },
  'sai-aga-ogshi': {
    slug: 'sai-aga-ogshi',
    nameZhTw: 'Ogshi女性毛髮營養補充品',
    nameJa: 'Ogshi（女性用毛髪サプリメント）',
    nameEn: 'Ogshi - Women Hair Supplement',
    descriptionZhTw: '日本女性專用·鐵/氨基酸/礦物質/維生素B群·國產高品質原料',
    priceJpy: 21168,
    category: 'cosmetic_surgery',
    sortOrder: 505,
  },
  'sai-aga-finasteride': {
    slug: 'sai-aga-finasteride',
    nameZhTw: 'Finasteride非那雄胺（男性AGA內服藥）',
    nameJa: 'フィナステリド（男性AGA内服薬）',
    nameEn: 'Finasteride - Male AGA Oral Medicine',
    descriptionZhTw: '抑制男性荷爾蒙·預防掉髮·1個月份',
    priceJpy: 19600,
    category: 'cosmetic_surgery',
    sortOrder: 506,
  },
  'sai-nutrition-light': {
    slug: 'sai-nutrition-light',
    nameZhTw: '精密營養分析 輕量方案（34項）',
    nameJa: 'オーソモレキュラー栄養解析 ライトプラン（34項目）',
    nameEn: 'Orthomolecular Nutrition - Light Plan (34 Items)',
    descriptionZhTw: '34項血液檢測+營養分析+結果說明+營養建議',
    priceJpy: 44000,
    category: 'cosmetic_surgery',
    sortOrder: 362,
  },
  'sai-nutrition-standard': {
    slug: 'sai-nutrition-standard',
    nameZhTw: '精密營養分析 標準方案（64項）',
    nameJa: 'オーソモレキュラー栄養解析 スタンダードプラン（64項目）',
    nameEn: 'Orthomolecular Nutrition - Standard Plan (64 Items)',
    descriptionZhTw: '64項血液檢測+營養分析+結果說明+營養建議',
    priceJpy: 90000,
    category: 'cosmetic_surgery',
    sortOrder: 363,
  },
  'sai-med-tranexamic': {
    slug: 'sai-med-tranexamic',
    nameZhTw: '傳明酸（30日份）',
    nameJa: 'トラネキサム酸（30日分）',
    nameEn: 'Tranexamic Acid - 30 Days',
    descriptionZhTw: '抗炎症·改善肝斑·美白·美肌效果',
    priceJpy: 6000,
    category: 'cosmetic_surgery',
    sortOrder: 510,
  },
  'sai-med-ubera': {
    slug: 'sai-med-ubera',
    nameZhTw: 'Ubera維生素E（30日份）',
    nameJa: 'ユベラ（30日分）',
    nameEn: 'Ubera Vitamin E - 30 Days',
    descriptionZhTw: '維生素E衍生物·抗氧化·促進肌膚代謝·改善色斑',
    priceJpy: 5600,
    category: 'cosmetic_surgery',
    sortOrder: 511,
  },
  'sai-med-goreisan': {
    slug: 'sai-med-goreisan',
    nameZhTw: '五苓散（7日份）',
    nameJa: '五苓散（7日分）',
    nameEn: 'Goreisan Herbal Medicine - 7 Days',
    descriptionZhTw: '術後消腫·排出體內多餘水分·改善浮腫',
    priceJpy: 4200,
    category: 'cosmetic_surgery',
    sortOrder: 512,
  },
  'sai-med-jumihaidokuto': {
    slug: 'sai-med-jumihaidokuto',
    nameZhTw: '十味敗毒湯（30日份）',
    nameJa: '十味敗毒湯（30日分）',
    nameEn: 'Jumihaidokuto Herbal - 30 Days',
    descriptionZhTw: '調節荷爾蒙平衡·控制皮脂分泌·改善成人痘痘',
    priceJpy: 7000,
    category: 'cosmetic_surgery',
    sortOrder: 513,
  },
  'sai-drip-whitening-600': {
    slug: 'sai-drip-whitening-600',
    nameZhTw: '白玉美白點滴（600mg）',
    nameJa: '白玉・美白点滴（600mg）',
    nameEn: 'Whitening IV Drip - 600mg',
    descriptionZhTw: '穀胱甘肽·抑制黑色素·美白·解毒·改善宿醉和慢性疲勞',
    priceJpy: 12000,
    category: 'cosmetic_surgery',
    sortOrder: 520,
  },
  'sai-drip-whitening-1200': {
    slug: 'sai-drip-whitening-1200',
    nameZhTw: '白玉美白點滴（1200mg）',
    nameJa: '白玉・美白点滴（1200mg）',
    nameEn: 'Whitening IV Drip - 1200mg',
    descriptionZhTw: '高劑量穀胱甘肽·更強效美白解毒',
    priceJpy: 18000,
    category: 'cosmetic_surgery',
    sortOrder: 521,
  },
  'sai-drip-vitc-10g': {
    slug: 'sai-drip-vitc-10g',
    nameZhTw: '高濃度維C點滴（10g）',
    nameJa: '高濃度ビタミンC点滴（10g）',
    nameEn: 'High-Dose Vitamin C IV - 10g',
    descriptionZhTw: '高濃度維生素C·美肌美白·抗氧化·免疫提升',
    priceJpy: 14000,
    category: 'cosmetic_surgery',
    sortOrder: 522,
  },
  'sai-drip-vitc-30g': {
    slug: 'sai-drip-vitc-30g',
    nameZhTw: '高濃度維C點滴（30g）',
    nameJa: '高濃度ビタミンC点滴（30g）',
    nameEn: 'High-Dose Vitamin C IV - 30g',
    descriptionZhTw: '超高濃度維生素C·需事前G6PD檢查',
    priceJpy: 38000,
    category: 'cosmetic_surgery',
    sortOrder: 523,
  },
  'sai-drip-vitc-40g': {
    slug: 'sai-drip-vitc-40g',
    nameZhTw: '高濃度維C點滴（40g）',
    nameJa: '高濃度ビタミンC点滴（40g）',
    nameEn: 'High-Dose Vitamin C IV - 40g',
    descriptionZhTw: '最高濃度維生素C·需事前G6PD檢查·疾病預防改善',
    priceJpy: 50000,
    category: 'cosmetic_surgery',
    sortOrder: 524,
  },
  'sai-drip-diet': {
    slug: 'sai-drip-diet',
    nameZhTw: '燃脂瘦身點滴',
    nameJa: '脂肪燃焼ダイエット点滴',
    nameEn: 'Fat Burning Diet IV Drip',
    descriptionZhTw: 'L-肉鹼+α-硫辛酸+維生素B·促進脂肪燃燒·抗氧化·改善疲勞冰冷',
    priceJpy: 18000,
    category: 'cosmetic_surgery',
    sortOrder: 525,
  },
  'sai-drip-cinderella': {
    slug: 'sai-drip-cinderella',
    nameZhTw: '灰姑娘點滴',
    nameJa: 'シンデレラ点滴',
    nameEn: 'Cinderella IV Drip',
    descriptionZhTw: '美白+燃脂雙效合一·肌膚和身材都像灰姑娘一樣',
    priceJpy: 26000,
    category: 'cosmetic_surgery',
    sortOrder: 526,
  },
  'sai-drip-fatigue': {
    slug: 'sai-drip-fatigue',
    nameZhTw: '疲勞恢復·壓力舒緩點滴',
    nameJa: '疲労回復・ストレスケア点滴',
    nameEn: 'Fatigue Recovery & Stress Care IV',
    descriptionZhTw: '維生素B群+甘草酸·快速恢復疲勞·解毒抗炎·宿醉腰痛也有效',
    priceJpy: 14000,
    category: 'cosmetic_surgery',
    sortOrder: 527,
  },
  'sai-drip-hangover': {
    slug: 'sai-drip-hangover',
    nameZhTw: '宿醉·肝機能改善點滴',
    nameJa: '二日酔い・肝機能改善点滴',
    nameEn: 'Hangover & Liver Function IV',
    descriptionZhTw: '幫助肝臟分解酒精·快速緩解宿醉·改善肝機能·疲勞倦怠',
    priceJpy: 14000,
    category: 'cosmetic_surgery',
    sortOrder: 528,
  },
  'sai-drip-custom': {
    slug: 'sai-drip-custom',
    nameZhTw: '院長訂製點滴',
    nameJa: '院長のオーダーメイド点滴',
    nameEn: 'Director Custom IV Drip',
    descriptionZhTw: '根據營養狀態/體調/目的·院長量身調配的特製雞尾酒點滴',
    priceJpy: 50000,
    category: 'cosmetic_surgery',
    sortOrder: 529,
  },
  'sai-drip-stemcell-fd': {
    slug: 'sai-drip-stemcell-fd',
    nameZhTw: '點滴 臍帶幹細胞上清液（凍乾）',
    nameJa: '点滴 臍帯幹細胞上清液（フリーズドライ）',
    nameEn: 'IV Drip - Umbilical Stem Cell (Freeze-Dried)',
    descriptionZhTw: '高再生能力·改善膚質/細紋/疲勞恢復/性機能',
    priceJpy: 166000,
    category: 'cosmetic_surgery',
    sortOrder: 530,
  },
  'sai-drip-stemcell-frozen': {
    slug: 'sai-drip-stemcell-frozen',
    nameZhTw: '點滴 臍帶幹細胞上清液（新鮮凍結）',
    nameJa: '点滴 臍帯幹細胞上清液（新鮮凍結品）',
    nameEn: 'IV Drip - Umbilical Stem Cell (Fresh Frozen)',
    descriptionZhTw: '新鮮凍結品10cc·最高品質再生療法',
    priceJpy: 700000,
    category: 'cosmetic_surgery',
    sortOrder: 531,
  },

  // ─── JTB 合作医院 共享咨询服务 ───
  'jtb-initial-consultation': {
    slug: 'jtb-initial-consultation',
    nameZhTw: 'JTB 合作醫院 - 前期諮詢服務',
    nameJa: 'JTB提携病院 - 初期相談サービス',
    nameEn: 'JTB Partner Hospital - Initial Consultation',
    descriptionZhTw: '資料翻譯、醫院諮詢、治療方案初步評估',
    priceJpy: 221000,
    category: 'other',
    sortOrder: 900,
  },
} as const;

/**
 * 获取套餐配置（用于前端展示）
 *
 * @param slug 套餐 slug
 * @returns 套餐配置，如果不存在返回 null
 */
export function getPackageConfig(slug: string): MedicalPackageConfig | null {
  return MEDICAL_PACKAGES[slug] || null;
}

/**
 * 获取所有套餐配置（用于前端列表展示）
 *
 * @returns 按 sortOrder 排序的套餐配置数组
 */
export function getAllPackageConfigs(): MedicalPackageConfig[] {
  return Object.values(MEDICAL_PACKAGES).sort((a, b) => a.sortOrder - b.sortOrder);
}

/**
 * 按分类获取套餐配置
 *
 * @param category 套餐分类
 * @returns 该分类下的所有套餐配置
 */
export function getPackagesByCategory(
  category: 'cancer_treatment' | 'health_checkup' | 'cosmetic_surgery' | 'other'
): MedicalPackageConfig[] {
  return getAllPackageConfigs().filter(pkg => pkg.category === category);
}

/**
 * 格式化价格显示
 *
 * @param priceJpy 日元价格
 * @param locale 语言
 * @returns 格式化后的价格字符串
 */
export function formatPrice(priceJpy: number, locale: string = 'zh-TW'): string {
  const formatter = new Intl.NumberFormat(locale, {
    style: 'currency',
    currency: 'JPY',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  });
  return formatter.format(priceJpy);
}
