-- =====================================================
-- 121: venues 官网一次性回填(单条 UPDATE,防粘贴截断)
-- =====================================================
-- 此前多份逐条 UPDATE 迁移疑似被 SQL 编辑器粘贴截断,只跑了前一部分。
-- 本迁移把全部 148 家压成【一条】UPDATE(VALUES 映射),要么整条成功、要么语法报错,
-- 不会"跑一半还显示 Success"。匹配时忽略全/半角空格。仅填 website_url 为空的行,幂等。
-- 末尾 SELECT 直接返回回填后的统计,跑完即见结果。
--
-- ⚠️ 本项目无迁移自动跟踪,需手动在生产库执行本文件。整份一次性粘贴运行。

UPDATE venues AS t
SET website_url = v.url
FROM (VALUES
  ('ある夜、ビルの片隅で', 'https://www.fankura.com/shop/shop_key/20154'),
  ('インタイトル 恵比寿', 'https://www.fankura.com/shop/shop_key/20137'),
  ('エマクラブ 江坂', 'https://www.fankura.com/shop/shop_key/20220'),
  ('エルミネ 新横浜', 'https://www.fankura.com/shop/shop_key/20111'),
  ('エルミネ 和歌山', 'https://www.fankura.com/shop/shop_key/20013'),
  ('ELENA HOUSE', 'https://www.fankura.com/shop/shop_key/20198'),
  ('エレナハウス 高知', 'https://www.fankura.com/shop/shop_key/20233'),
  ('エレナハウス 梅田', 'https://www.fankura.com/shop/shop_key/20212'),
  ('ELENA HOUSE 京都', 'https://www.fankura.com/shop/shop_key/20199'),
  ('エンジェルフェザー ミナミ', 'https://www.fankura.com/shop/shop_key/20269'),
  ('エンジェル・フェザー 池袋', 'https://www.fankura.com/shop/shop_key/20138'),
  ('エンジェル・フェザー 北新地', 'https://www.fankura.com/shop/shop_key/20046'),
  ('エンジェル・フェザー 神戸', 'https://www.fankura.com/shop/shop_key/20203'),
  ('エンジェル・フェザー 仙台', 'https://www.fankura.com/shop/shop_key/20125'),
  ('錵乃音 京都', 'https://www.fankura.com/shop/shop_key/20040'),
  ('錵乃音 祇園', 'https://www.fankura.com/shop/shop_key/20041'),
  ('錵乃音 神戸', 'https://www.fankura.com/shop/shop_key/20039'),
  ('錵乃音 和歌山', 'https://www.fankura.com/shop/shop_key/20171'),
  ('川崎 Garden', 'https://www.fankura.com/shop/shop_key/20172'),
  ('神田茶屋', 'https://www.fankura.com/shop/shop_key/20160'),
  ('ジェム 立川', 'https://www.fankura.com/shop/shop_key/20155'),
  ('KATY STUDIO', 'https://www.fankura.com/shop/shop_key/20195'),
  ('ゴールドトリガー仙台', 'https://www.fankura.com/shop/shop_key/20243'),
  ('サンセットラウンジェット 四日市', 'https://www.fankura.com/shop/shop_key/20226'),
  ('サンセットラウンジェット 金沢', 'https://www.fankura.com/shop/shop_key/20107'),
  ('サンセットラウンジェット 祇園', 'https://www.fankura.com/shop/shop_key/20104'),
  ('サンセットラウンジェット 神戸', 'https://www.fankura.com/shop/shop_key/20133'),
  ('サンセットラウンジェット 新橋', 'https://www.fankura.com/shop/shop_key/20254'),
  ('ザ・バーレスク', 'https://www.fankura.com/shop/shop_key/20097'),
  ('シークレットガーデン京都', 'https://www.fankura.com/shop/shop_key/20123'),
  ('翠彩', 'https://www.fankura.com/shop/shop_key/20257'),
  ('シークレットガーデン 神戸', 'https://www.fankura.com/shop/shop_key/10424'),
  ('シークレットガーデン 西中島', 'https://www.fankura.com/shop/shop_key/45'),
  ('シャトリス', 'https://www.fankura.com/shop/shop_key/20235'),
  ('XEE', 'https://www.fankura.com/shop/shop_key/20250'),
  ('ジェム 錦', 'https://www.fankura.com/shop/shop_key/20261'),
  ('ジェム 川崎', 'https://www.fankura.com/shop/shop_key/20192'),
  ('ジェムサロン 岡山', 'https://www.fankura.com/shop/shop_key/20267'),
  ('ジェムサロン 草津', 'https://www.fankura.com/shop/shop_key/20219'),
  ('ジェムサロン 町田', 'https://www.fankura.com/shop/shop_key/20118'),
  ('ジェム 新横浜', 'https://www.fankura.com/shop/shop_key/20209'),
  ('ジェム四日市', 'https://www.fankura.com/shop/shop_key/20211'),
  ('ZOO 東京', 'https://www.fankura.com/shop/shop_key/20116'),
  ('ZOO 金沢', 'https://www.fankura.com/shop/shop_key/159'),
  ('ZOO 京都', 'https://www.fankura.com/shop/shop_key/20237'),
  ('ZOO 神戸', 'https://www.fankura.com/shop/shop_key/21'),
  ('ZOO 仙台', 'https://www.fankura.com/shop/shop_key/20075'),
  ('ZOO ミナミ', 'https://www.fankura.com/shop/shop_key/25'),
  ('17マイルドライブ 加古川', 'https://www.fankura.com/shop/shop_key/20140'),
  ('17MAP', 'https://www.fankura.com/shop/shop_key/20190'),
  ('禅の月', 'https://www.fankura.com/shop/shop_key/20258'),
  ('チャリンコ 加古川', 'https://www.fankura.com/shop/shop_key/20185'),
  ('チャリンコ 十三', 'https://www.fankura.com/shop/shop_key/20206'),
  ('TSUKI NO KITANOZAKA', 'https://www.fankura.com/shop/shop_key/20182'),
  ('テラスグリーン', 'https://www.fankura.com/shop/shop_key/20174'),
  ('ドルチェガールズ', 'https://www.fankura.com/shop/shop_key/20253'),
  ('ドルチェラグレス', 'https://www.fankura.com/shop/shop_key/20242'),
  ('ドレスライン 立川', 'https://www.fankura.com/shop/shop_key/20115'),
  ('ナルシス', 'https://www.fankura.com/shop/shop_key/20173'),
  ('NANSHIKA YAMATOYA', 'https://www.fankura.com/shop/shop_key/20259'),
  ('バニーバーチャリンコ', 'https://www.fankura.com/shop/shop_key/20139'),
  ('バニーバーチャリンコ 高松', 'https://www.fankura.com/shop/shop_key/20181'),
  ('バニーバーチャリンコ 四日市', 'https://www.fankura.com/shop/shop_key/20224'),
  ('バニーバーチャリンコ 奈良', 'https://www.fankura.com/shop/shop_key/20193'),
  ('バニーラウンジB4', 'https://www.fankura.com/shop/shop_key/20202'),
  ('バニーラウンジB4 上野', 'https://www.fankura.com/shop/shop_key/20252'),
  ('バンチオブローゼス 岐阜', 'https://www.fankura.com/shop/shop_key/20161'),
  ('バンチオブローゼス 西中島', 'https://www.fankura.com/shop/shop_key/20165'),
  ('B4 赤坂', 'https://www.fankura.com/shop/shop_key/20231'),
  ('B4 京都', 'https://www.fankura.com/shop/shop_key/20232'),
  ('B4 草津', 'https://www.fankura.com/shop/shop_key/20249'),
  ('B4 仙台', 'https://www.fankura.com/shop/shop_key/20270'),
  ('B4 立川', 'https://www.fankura.com/shop/shop_key/20248'),
  ('B4 広島', 'https://www.fankura.com/shop/shop_key/20251'),
  ('B4 町田', 'https://www.fankura.com/shop/shop_key/20230'),
  ('B4 上野', 'https://www.fankura.com/shop/shop_key/20241'),
  ('B4 梅田', 'https://www.fankura.com/shop/shop_key/20207'),
  ('B4 神田', 'https://www.fankura.com/shop/shop_key/20196'),
  ('B4 新橋', 'https://www.fankura.com/shop/shop_key/20208'),
  ('美人茶屋 上野', 'https://www.fankura.com/shop/shop_key/20191'),
  ('美人茶屋 梅田', 'https://www.fankura.com/shop/shop_key/20244'),
  ('美人茶屋 岡山', 'https://www.fankura.com/shop/shop_key/20221'),
  ('美人茶屋 金沢', 'https://www.fankura.com/shop/shop_key/20168'),
  ('美人茶屋 新橋', 'https://www.fankura.com/shop/shop_key/20228'),
  ('美人茶屋 高松', 'https://www.fankura.com/shop/shop_key/20217'),
  ('美人茶屋 北新地', 'https://www.fankura.com/shop/shop_key/20163'),
  ('美人茶屋 新宿', 'https://www.fankura.com/shop/shop_key/20126'),
  ('美人茶屋 六本木', 'https://www.fankura.com/shop/shop_key/20121'),
  ('美人茶屋 祇園', 'https://www.fankura.com/shop/shop_key/20102'),
  ('美人茶屋 神戸', 'https://www.fankura.com/shop/shop_key/10411'),
  ('美人茶屋 広島', 'https://www.fankura.com/shop/shop_key/10412'),
  ('美人茶屋 ミナミ', 'https://www.fankura.com/shop/shop_key/215'),
  ('ビゼ 上野', 'https://www.fankura.com/shop/shop_key/20215'),
  ('ビゼ 新宿', 'https://www.fankura.com/shop/shop_key/20238'),
  ('ビゼ 中洲', 'https://www.fankura.com/shop/shop_key/20234'),
  ('ビゼ 広島', 'https://www.fankura.com/shop/shop_key/20262'),
  ('ビゼ 池袋', 'https://www.fankura.com/shop/shop_key/20098'),
  ('ビゼ 北新地', 'https://www.fankura.com/shop/shop_key/20047'),
  ('ビゼ 祇園', 'https://www.fankura.com/shop/shop_key/10418'),
  ('ビゼ ミナミ', 'https://www.fankura.com/shop/shop_key/20049'),
  ('ピースオブチョコレート 仙台', 'https://www.fankura.com/shop/shop_key/20180'),
  ('ピースオブチョコレート 広島', 'https://www.fankura.com/shop/shop_key/20179'),
  ('フィッツ 岐阜', 'https://www.fankura.com/shop/shop_key/20051'),
  ('フィッツ 神戸', 'https://www.fankura.com/shop/shop_key/20003'),
  ('フィッツ 奈良', 'https://www.fankura.com/shop/shop_key/10422'),
  ('ベロア 岡山', 'https://www.fankura.com/shop/shop_key/20229'),
  ('ベロア 北新地', 'https://www.fankura.com/shop/shop_key/20189'),
  ('ベロア 神戸', 'https://www.fankura.com/shop/shop_key/20164'),
  ('ベロア 仙台', 'https://www.fankura.com/shop/shop_key/20170'),
  ('ベロア 錦', 'https://www.fankura.com/shop/shop_key/20239'),
  ('ベロア 十三', 'https://www.fankura.com/shop/shop_key/20204'),
  ('ポニーテール 堺東', 'https://www.fankura.com/shop/shop_key/37'),
  ('ミスト ミナミ', 'https://www.fankura.com/shop/shop_key/20050'),
  ('ミュゼルヴァ 中洲', 'https://www.fankura.com/shop/shop_key/20266'),
  ('ミュゼルヴァ 六本木', 'https://www.fankura.com/shop/shop_key/20114'),
  ('ミュゼルヴァ 北新地', 'https://www.fankura.com/shop/shop_key/20001'),
  ('ミュゼルヴァ 祇園', 'https://www.fankura.com/shop/shop_key/20048'),
  ('ミュゼルヴァ 神戸', 'https://www.fankura.com/shop/shop_key/20150'),
  ('ミュゼルヴァ 広島', 'https://www.fankura.com/shop/shop_key/20143'),
  ('ミュゼルヴァ ミナミ', 'https://www.fankura.com/shop/shop_key/20147'),
  ('ミリブルー 高槻', 'https://www.fankura.com/shop/shop_key/20223'),
  ('ミリルージュ 布施', 'https://www.fankura.com/shop/shop_key/20222'),
  ('ミリルージュ 京橋', 'https://www.fankura.com/shop/shop_key/20236'),
  ('柳ヶ瀬 Garden', 'https://www.fankura.com/shop/shop_key/20176'),
  ('ゆめうつつ', 'https://www.fankura.com/shop/shop_key/20130'),
  ('夢露地 祇園', 'https://www.fankura.com/shop/shop_key/20218'),
  ('夢露地 神戸', 'https://www.fankura.com/shop/shop_key/20268'),
  ('夢露地 ミナミ', 'https://www.fankura.com/shop/shop_key/20225'),
  ('夢露地 四日市', 'https://www.fankura.com/shop/shop_key/20247'),
  ('夢露地 金沢', 'https://www.fankura.com/shop/shop_key/20210'),
  ('ラ・ポッチャポッチャ', 'https://www.fankura.com/shop/shop_key/10415'),
  ('ラ・レーヌ・ゴート', 'https://www.fankura.com/shop/shop_key/20256'),
  ('リブレット', 'https://www.fankura.com/shop/shop_key/10419'),
  ('ワールドトリップ 広島', 'https://www.fankura.com/shop/shop_key/20169'),
  ('ヴォレ 梅田', 'https://www.fankura.com/shop/shop_key/20081'),
  ('大阪メルヘン', 'http://www.osaka-merhen.jp/'),
  ('カラオケ&ダイニング ブルームラウンジ', 'http://bloom-lounge.com/'),
  ('クラブ・ラウンジ ベルベージュ', 'http://bellebeige.com/'),
  ('クラブ桔梗 祇園邸', 'http://club-kikyo.com/'),
  ('クロリス 六本木', 'http://www.club-chloris.com/'),
  ('月ノ湊', 'http://club-tsukinosou.com/'),
  ('ドアラウンジ 北新地', 'http://www.doorlounge-n.com/'),
  ('ビーノワール 六本木', 'http://www.wine-bar-bb.com/'),
  ('美ノ間 六本木', 'http://www.club-binoma.com/'),
  ('ルームラウンジダジール', 'http://room-lounge-dasyl.com/'),
  ('ヴォレ 京橋', 'https://www.fankura.com/shop/shop_key/20141'),
  ('エマクラブ 中洲', 'https://www.amaclub-nakasu.com/'),
  ('メルセゾン', 'https://www.club-mersaison.com/')
) AS v(name, url)
WHERE replace(replace(t.name, '　', ''), ' ', '') = replace(replace(v.name, '　', ''), ' ', '')
  AND t.website_url IS NULL;

-- 回填结果(跑完看这行):
SELECT count(*) AS 总店数, count(website_url) AS 已填官网, count(*) - count(website_url) AS 仍留空 FROM venues;
